// seed/auditLogs.ts — 감사 로그 시드 데이터 (최소 30개)

import type { AuditLog } from '../domain/types'

const daysAgo = (d: number, h = 0) =>
  new Date(Date.now() - d * 86400000 - h * 3600000).toISOString()

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    category: '승인',
    title: '운영자 승인 처리',
    operatorId: 'op-002',
    operatorName: '한강수영클럽',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(0, 2),
    impact: 'medium',
    detail: '신규 운영자 가입 신청 검토 후 승인 처리',
    reason: '서류 검토 완료. 사업자등록증 확인됨.',
    metadata: {},
  },
  {
    id: 'log-002',
    category: '결제',
    title: '결제 실패 수동 처리',
    operatorId: 'op-003',
    operatorName: '강남아쿠아스쿨',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(0, 4),
    impact: 'high',
    detail: '카드 만료로 인한 결제 실패 — 운영자에게 카드 변경 요청 발송',
    reason: '카드 만료일 경과',
    metadata: { failCount: 2, amount: 10000 },
  },
  {
    id: 'log-003',
    category: 'grace',
    title: 'Grace 기간 적용',
    operatorId: 'op-004',
    operatorName: '분당스포츠센터',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(1),
    impact: 'medium',
    detail: '결제 실패 후 7일 Grace 기간 적용. 카드 교체 진행 중.',
    reason: '장기 고객 유지. 카드 교체 협의 완료.',
    metadata: { graceDays: 7 },
  },
  {
    id: 'log-004',
    category: '읽기전용',
    title: '읽기전용 전환',
    operatorId: 'op-005',
    operatorName: '인천수영학원',
    actorName: '시스템',
    createdAt: daysAgo(3),
    impact: 'high',
    detail: '구독 해지 확인 후 읽기전용 자동 전환. 업로드 차단.',
    reason: '구독 해지 처리',
    metadata: {},
  },
  {
    id: 'log-005',
    category: '저장공간',
    title: '저장공간 95% 초과 업로드 차단',
    operatorId: 'op-006',
    operatorName: '부산마린수영클럽',
    actorName: '시스템',
    createdAt: daysAgo(0, 1),
    impact: 'critical',
    detail: '저장공간 96% 초과로 업로드 자동 차단. 운영자 알림 발송.',
    reason: '저장 정책 임계값 초과',
    metadata: { usedMb: 29491, totalMb: 30720, percent: 96 },
  },
  {
    id: 'log-006',
    category: '플랜변경',
    title: '플랜 변경: 스탠다드 → 어드밴스',
    operatorId: 'op-007',
    operatorName: '대전아쿠아클럽',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(14),
    impact: 'medium',
    detail: '활성회원 증가로 100명 한도 도달. 300명 플랜으로 업그레이드.',
    reason: '운영자 요청',
    metadata: { fromPlan: '스탠다드', toPlan: '어드밴스', priceDiff: 5000 },
  },
  {
    id: 'log-007',
    category: '정책',
    title: '환불 정책 버전 업데이트',
    operatorId: '',
    operatorName: '전체',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(20),
    impact: 'high',
    detail: '환불 정책 v1.2 → v1.3 개정. 구독 하향 시 크레딧 적립 조항 추가.',
    reason: '정책 명확화',
    metadata: { fromVersion: 'v1.2', toVersion: 'v1.3' },
  },
  {
    id: 'log-008',
    category: '기능플래그',
    title: '기능 플래그 활성화: new_subscription_policy',
    operatorId: '',
    operatorName: '전체',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(7),
    impact: 'high',
    detail: '신규 구독 정책 기능 플래그 전역 활성화.',
    reason: '안정성 테스트 완료',
    metadata: { flagKey: 'new_subscription_policy', enabled: true },
  },
  {
    id: 'log-009',
    category: '고객센터',
    title: '고객 티켓 상태 변경: 접수 → 처리중',
    operatorId: 'op-003',
    operatorName: '강남아쿠아스쿨',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(2),
    impact: 'low',
    detail: '결제 실패 관련 문의 접수. 담당자 배정 후 처리 시작.',
    reason: '',
    metadata: { ticketId: 'tkt-003' },
  },
  {
    id: 'log-010',
    category: '스냅샷',
    title: '플랫폼 전체 스냅샷 생성',
    operatorId: '',
    operatorName: '전체',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(7),
    impact: 'medium',
    detail: '주간 전체 스냅샷 생성. 운영자 14개 기준.',
    reason: '정기 백업',
    metadata: { snapshotId: 'snap-001', sizeMb: 2048 },
  },
  {
    id: 'log-011',
    category: '삭제예약',
    title: '자동삭제 예약: 24시간 후',
    operatorId: 'op-010',
    operatorName: '울산마스터즈',
    actorName: '시스템',
    createdAt: daysAgo(0, 3),
    impact: 'critical',
    detail: '구독 해지 24시간 후 사진/영상 자동삭제 예약. 텍스트는 유지.',
    reason: '구독 해지 정책',
    metadata: { deleteAt: new Date(Date.now() + 86400000).toISOString() },
  },
  {
    id: 'log-012',
    category: '업로드차단',
    title: '업로드 차단 수동 적용',
    operatorId: 'op-012',
    operatorName: '제주오션수영장',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(7),
    impact: 'high',
    detail: '차지백 발생으로 임시 업로드 차단 조치.',
    reason: '차지백 분쟁 진행 중',
    metadata: {},
  },
  {
    id: 'log-013',
    category: '승인',
    title: '운영자 승인 처리',
    operatorId: 'op-009',
    operatorName: '수원레저수영장',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(240),
    impact: 'medium',
    detail: '수원레저수영장 가입 승인.',
    reason: '서류 검토 완료.',
    metadata: {},
  },
  {
    id: 'log-014',
    category: '크레딧',
    title: '크레딧 수동 적립',
    operatorId: 'op-009',
    operatorName: '수원레저수영장',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(25),
    impact: 'medium',
    detail: '플랜 하향 시 미사용 잔여금 크레딧으로 적립. 10,000원.',
    reason: '플랜 하향 정책',
    metadata: { amount: 10000 },
  },
  {
    id: 'log-015',
    category: '기능플래그',
    title: '기능 플래그 비활성화: auto_deletion_policy',
    operatorId: '',
    operatorName: '전체',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(30),
    impact: 'high',
    detail: '자동삭제 정책 플래그 임시 비활성화. 법무팀 검토 요청.',
    reason: '법무팀 검토 중',
    metadata: { flagKey: 'auto_deletion_policy', enabled: false },
  },
  {
    id: 'log-016',
    category: '복구',
    title: '복구 시뮬레이션 생성',
    operatorId: 'op-010',
    operatorName: '울산마스터즈',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(1),
    impact: 'high',
    detail: '데이터 복구 시뮬레이션 실행. dual_compare 모드.',
    reason: '삭제 전 확인',
    metadata: { mode: 'dual_compare', snapshotId: 'snap-005' },
  },
  {
    id: 'log-017',
    category: '승인',
    title: '운영자 반려 처리',
    operatorId: '',
    operatorName: '테스트코치',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(15),
    impact: 'medium',
    detail: '사업자등록증 서류 불일치로 반려.',
    reason: '서류 불일치',
    metadata: {},
  },
  {
    id: 'log-018',
    category: '고객센터',
    title: '고객 티켓 해결',
    operatorId: 'op-007',
    operatorName: '대전아쿠아클럽',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(10),
    impact: 'low',
    detail: '저장공간 80% 경고 관련 문의 해결. 업그레이드 권유.',
    reason: '',
    metadata: { ticketId: 'tkt-007' },
  },
  {
    id: 'log-019',
    category: '저장공간',
    title: '저장공간 추가 적용',
    operatorId: 'op-011',
    operatorName: '스포츠플러스 프랜차이즈',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(45),
    impact: 'medium',
    detail: '엔터프라이즈 계약 기준 추가 저장 100GB 적용.',
    reason: '계약 협의 완료',
    metadata: { extraStorageMb: 102400 },
  },
  {
    id: 'log-020',
    category: '읽기전용',
    title: '플랫폼 읽기전용 해제',
    operatorId: '',
    operatorName: '전체',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(60),
    impact: 'critical',
    detail: '점검 완료 후 플랫폼 읽기전용 해제.',
    reason: '서버 점검 종료',
    metadata: {},
  },
  {
    id: 'log-021',
    category: '플랜변경',
    title: '플랜 변경: 무료 → 스탠다드',
    operatorId: 'op-008',
    operatorName: '광주수영교실',
    actorName: '시스템',
    createdAt: daysAgo(5),
    impact: 'medium',
    detail: '무료 회원 한도(5명) 초과로 스탠다드 플랜 자동 안내. 운영자 선택 대기.',
    reason: '한도 초과',
    metadata: { fromPlan: '무료', toPlan: '스탠다드' },
  },
  {
    id: 'log-022',
    category: '스냅샷',
    title: '킬스위치 직전 스냅샷 생성',
    operatorId: 'op-010',
    operatorName: '울산마스터즈',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(0, 6),
    impact: 'critical',
    detail: '데이터 삭제 실행 전 강제 스냅샷 생성 완료.',
    reason: '삭제 전 보존',
    metadata: { snapshotId: 'snap-008' },
  },
  {
    id: 'log-023',
    category: '결제',
    title: 'Grace 기간 종료 → readonly 전환',
    operatorId: 'op-010',
    operatorName: '울산마스터즈',
    actorName: '시스템',
    createdAt: daysAgo(5),
    impact: 'critical',
    detail: 'Grace 기간 만료. 결제 미처리로 읽기전용 + 자동삭제 예약.',
    reason: 'Grace 만료',
    metadata: {},
  },
  {
    id: 'log-024',
    category: '고객센터',
    title: '환불 요청 검토',
    operatorId: 'op-005',
    operatorName: '인천수영학원',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(4),
    impact: 'high',
    detail: '해지 후 크레딧 환불 요청. 5,000원 검토 완료.',
    reason: '해지 정책 적용',
    metadata: { refundAmount: 5000 },
  },
  {
    id: 'log-025',
    category: '기능플래그',
    title: '기능 플래그 운영자별 예외 적용',
    operatorId: 'op-011',
    operatorName: '스포츠플러스 프랜차이즈',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(10),
    impact: 'medium',
    detail: 'new_scheduler 기능 플래그 운영자별 조기 활성화.',
    reason: '엔터프라이즈 파트너 사전 테스트',
    metadata: { flagKey: 'new_scheduler', operatorId: 'op-011' },
  },
  {
    id: 'log-026',
    category: '저장공간',
    title: '업로드 급증 감지',
    operatorId: 'op-009',
    operatorName: '수원레저수영장',
    actorName: '시스템',
    createdAt: daysAgo(1),
    impact: 'medium',
    detail: '7일간 820MB 업로드 급증 감지. 관리자 알림 발송.',
    reason: '임계값 초과',
    metadata: { growth7dMb: 820 },
  },
  {
    id: 'log-027',
    category: '정책',
    title: '개인정보 처리방침 버전 업데이트',
    operatorId: '',
    operatorName: '전체',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(45),
    impact: 'high',
    detail: '개인정보 처리방침 v2.0 공시. 전체 운영자 재동의 요청.',
    reason: '법령 개정 대응',
    metadata: { fromVersion: 'v1.9', toVersion: 'v2.0' },
  },
  {
    id: 'log-028',
    category: '결제',
    title: '재청구 시도 (mock)',
    operatorId: 'op-012',
    operatorName: '제주오션수영장',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(3),
    impact: 'high',
    detail: '결제 실패 후 수동 재청구 요청. PG mock 처리.',
    reason: '결제 실패 처리',
    metadata: { amount: 5000 },
  },
  {
    id: 'log-029',
    category: '승인',
    title: '운영자 계정 제한 적용',
    operatorId: 'op-012',
    operatorName: '제주오션수영장',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(7),
    impact: 'high',
    detail: '차지백 발생 및 반복 환불 요청으로 계정 제한 상태 전환.',
    reason: '차지백 분쟁',
    metadata: {},
  },
  {
    id: 'log-030',
    category: '스냅샷',
    title: '운영자 개별 스냅샷 생성',
    operatorId: 'op-003',
    operatorName: '강남아쿠아스쿨',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(2),
    impact: 'medium',
    detail: '결제 실패 처리 전 개별 스냅샷 생성.',
    reason: '데이터 보호',
    metadata: { snapshotId: 'snap-007', sizeMb: 342 },
  },
  {
    id: 'log-031',
    category: '고객센터',
    title: '기술팀 이슈 승격',
    operatorId: 'op-006',
    operatorName: '부산마린수영클럽',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(0, 5),
    impact: 'high',
    detail: '업로드 오류 반복 신고. 기술팀 이슈로 승격 처리.',
    reason: '기술 문제 확인',
    metadata: { ticketId: 'tkt-006' },
  },
  {
    id: 'log-032',
    category: '읽기전용',
    title: '플랫폼 읽기전용 적용 (점검)',
    operatorId: '',
    operatorName: '전체',
    actorName: '슈퍼관리자',
    createdAt: daysAgo(60),
    impact: 'critical',
    detail: '서버 긴급 점검. 전체 플랫폼 읽기전용 2시간 적용.',
    reason: '긴급 서버 점검',
    metadata: { durationHours: 2 },
  },
]
