// seed/backups.ts — 백업 스냅샷 시드 (최소 8개)

import type { BackupSnapshot } from '../domain/types'

const daysAgo = (d: number, h = 0) =>
  new Date(Date.now() - d * 86400000 - h * 3600000).toISOString()

const DEFAULT_INCLUDES = [
  'operator_info',
  'member_core',
  'subscription',
  'credit',
  'policy_docs',
  'attendance',
  'journal_text',
  'logs',
  'permissions',
  'feature_flags',
]

export const SEED_BACKUPS: BackupSnapshot[] = [
  {
    id: 'snap-001',
    bucket: 'platform_shadow_backup',
    scope: 'platform',
    operatorId: '',
    operatorName: '전체 플랫폼',
    createdAt: daysAgo(7),
    createdBy: '슈퍼관리자',
    includes: DEFAULT_INCLUDES,
    checksum: 'sha256:a1b2c3d4e5f6',
    note: '주간 정기 전체 스냅샷. 운영자 14개.',
    sizeMb: 2048,
    status: 'done',
  },
  {
    id: 'snap-002',
    bucket: 'platform_shadow_backup',
    scope: 'platform',
    operatorId: '',
    operatorName: '전체 플랫폼',
    createdAt: daysAgo(14),
    createdBy: '슈퍼관리자',
    includes: DEFAULT_INCLUDES,
    checksum: 'sha256:b2c3d4e5f6a1',
    note: '주간 정기 전체 스냅샷.',
    sizeMb: 1920,
    status: 'done',
  },
  {
    id: 'snap-003',
    bucket: 'platform_shadow_backup',
    scope: 'platform',
    operatorId: '',
    operatorName: '전체 플랫폼',
    createdAt: daysAgo(21),
    createdBy: '슈퍼관리자',
    includes: DEFAULT_INCLUDES,
    checksum: 'sha256:c3d4e5f6a1b2',
    note: '주간 정기 전체 스냅샷.',
    sizeMb: 1790,
    status: 'done',
  },
  {
    id: 'snap-004',
    bucket: 'operator_snapshot',
    scope: 'operator',
    operatorId: 'op-004',
    operatorName: '분당스포츠센터',
    createdAt: daysAgo(5),
    createdBy: '슈퍼관리자',
    includes: ['operator_info', 'member_core', 'subscription', 'credit', 'attendance', 'journal_text'],
    checksum: 'sha256:d4e5f6a1b2c3',
    note: 'Grace 기간 전 안전 스냅샷.',
    sizeMb: 512,
    status: 'done',
  },
  {
    id: 'snap-005',
    bucket: 'operator_snapshot',
    scope: 'operator',
    operatorId: 'op-010',
    operatorName: '울산마스터즈',
    createdAt: daysAgo(1),
    createdBy: '슈퍼관리자',
    includes: DEFAULT_INCLUDES,
    checksum: 'sha256:e5f6a1b2c3d4',
    note: '자동삭제 실행 전 복구용 스냅샷. dual_compare 복구 시뮬레이션 연결.',
    sizeMb: 394,
    status: 'done',
  },
  {
    id: 'snap-006',
    bucket: 'operator_snapshot',
    scope: 'operator',
    operatorId: 'op-005',
    operatorName: '인천수영학원',
    createdAt: daysAgo(3),
    createdBy: '슈퍼관리자',
    includes: ['operator_info', 'member_core', 'subscription', 'credit', 'policy_docs'],
    checksum: 'sha256:f6a1b2c3d4e5',
    note: '해지 처리 전 스냅샷.',
    sizeMb: 218,
    status: 'done',
  },
  {
    id: 'snap-007',
    bucket: 'operator_snapshot',
    scope: 'operator',
    operatorId: 'op-003',
    operatorName: '강남아쿠아스쿨',
    createdAt: daysAgo(2),
    createdBy: '슈퍼관리자',
    includes: ['operator_info', 'member_core', 'subscription', 'credit'],
    checksum: 'sha256:a2b3c4d5e6f7',
    note: '결제 실패 처리 전 스냅샷.',
    sizeMb: 342,
    status: 'done',
  },
  {
    id: 'snap-008',
    bucket: 'operator_snapshot',
    scope: 'operator',
    operatorId: 'op-010',
    operatorName: '울산마스터즈',
    createdAt: daysAgo(0, 6),
    createdBy: '슈퍼관리자',
    includes: DEFAULT_INCLUDES,
    checksum: 'sha256:b3c4d5e6f7a2',
    note: '킬스위치 실행 직전 강제 스냅샷. 복구 불가 경고 확인됨.',
    sizeMb: 396,
    status: 'done',
  },
]
