// seed/featureFlags.ts — 기능 플래그 시드 (최소 8개)

import type { FeatureFlag } from '../domain/types'

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString()

export const SEED_FEATURE_FLAGS: FeatureFlag[] = [
  {
    id: 'ff-001',
    key: 'new_scheduler',
    name: '신규 스케줄러',
    description: '새로운 수업 스케줄링 엔진 활성화. 반복 수업 패턴 지원.',
    scope: 'global',
    operatorId: '',
    enabled: false,
    updatedAt: daysAgo(10),
    updatedBy: '슈퍼관리자',
    reason: '안정성 추가 검토 필요. 일부 엣지케이스 미해결.',
  },
  {
    id: 'ff-002',
    key: 'new_subscription_policy',
    name: '신규 구독 정책',
    description: '하향 플랜 변경 시 크레딧 자동 적립, 즉시 적용 로직 개선.',
    scope: 'global',
    operatorId: '',
    enabled: true,
    updatedAt: daysAgo(7),
    updatedBy: '슈퍼관리자',
    reason: '안정성 테스트 완료. 전역 활성화.',
  },
  {
    id: 'ff-003',
    key: 'auto_deletion_policy',
    name: '자동삭제 정책',
    description: '구독 해지 24시간 후 사진/영상 자동삭제 정책 실행.',
    scope: 'global',
    operatorId: '',
    enabled: true,
    updatedAt: daysAgo(30),
    updatedBy: '슈퍼관리자',
    reason: '법무팀 검토 완료. 정책 반영.',
  },
  {
    id: 'ff-004',
    key: 'support_center_v2',
    name: '고객센터 v2',
    description: '고객센터 개편 버전. SLA 자동 계산, 담당자 자동 배정.',
    scope: 'global',
    operatorId: '',
    enabled: true,
    updatedAt: daysAgo(14),
    updatedBy: '슈퍼관리자',
    reason: '기능 안정화 완료.',
  },
  {
    id: 'ff-005',
    key: 'new_upload_structure',
    name: '신규 업로드 구조',
    description: '공통 업로드 후 무료/유료 버전 분리 처리 구조.',
    scope: 'global',
    operatorId: '',
    enabled: false,
    updatedAt: daysAgo(21),
    updatedBy: '슈퍼관리자',
    reason: 'R2 연동 전까지 mock 상태 유지.',
  },
  {
    id: 'ff-006',
    key: 'upload_spike_detection',
    name: '업로드 급증 감지',
    description: '7일간 업로드 급증 시 관리자 알림 및 플래그 자동 설정.',
    scope: 'global',
    operatorId: '',
    enabled: true,
    updatedAt: daysAgo(5),
    updatedBy: '슈퍼관리자',
    reason: '운영 모니터링 강화.',
  },
  {
    id: 'ff-007',
    key: 'readonly_auto_trigger',
    name: '읽기전용 자동 전환',
    description: 'Grace 기간 만료 시 자동 읽기전용 전환 및 자동삭제 예약.',
    scope: 'global',
    operatorId: '',
    enabled: true,
    updatedAt: daysAgo(60),
    updatedBy: '슈퍼관리자',
    reason: '구독 정책 자동화.',
  },
  {
    id: 'ff-008',
    key: 'credit_auto_apply',
    name: '크레딧 자동 적용',
    description: '다음 결제 시 크레딧 자동 차감 처리.',
    scope: 'global',
    operatorId: '',
    enabled: true,
    updatedAt: daysAgo(14),
    updatedBy: '슈퍼관리자',
    reason: '결제 편의성 개선.',
  },
  {
    id: 'ff-009',
    key: 'new_scheduler',
    name: '신규 스케줄러 (운영자 예외)',
    description: 'enterprise 운영자 조기 활성화 예외.',
    scope: 'operator',
    operatorId: 'op-011',
    enabled: true,
    updatedAt: daysAgo(10),
    updatedBy: '슈퍼관리자',
    reason: '엔터프라이즈 파트너 사전 테스트 요청.',
  },
]
