// seed/media.ts — 미디어 에셋 시드

import type { MediaAsset } from '../domain/types'

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString()

export const SEED_MEDIA: MediaAsset[] = [
  {
    id: 'media-001',
    operatorId: 'op-002',
    journalId: 'journal-101',
    classId: 'class-201',
    studentId: null,
    visibility: 'class_all',
    status: 'ready',
    originalInputSizeMb: 4.2,
    previewFreeSizeMb: 1.05,
    previewPaidSizeMb: 3.36,
    originalKey: 'op-002/originals/photo-001.jpg',
    previewFreeKey: 'op-002/free/photo-001-low.jpg',
    previewPaidKey: 'op-002/paid/photo-001-hd.jpg',
    sourceLabel: '수업일지 사진',
    createdAt: daysAgo(3),
  },
  {
    id: 'media-002',
    operatorId: 'op-002',
    journalId: null,
    classId: 'class-202',
    studentId: 'student-301',
    visibility: 'student_only',
    status: 'ready',
    originalInputSizeMb: 2.8,
    previewFreeSizeMb: 0.7,
    previewPaidSizeMb: 2.24,
    originalKey: 'op-002/originals/photo-002.jpg',
    previewFreeKey: 'op-002/free/photo-002-low.jpg',
    previewPaidKey: 'op-002/paid/photo-002-hd.jpg',
    sourceLabel: '개인 앨범',
    createdAt: daysAgo(5),
  },
  {
    id: 'media-003',
    operatorId: 'op-006',
    journalId: 'journal-102',
    classId: 'class-203',
    studentId: null,
    visibility: 'class_all',
    status: 'ready',
    originalInputSizeMb: 6.1,
    previewFreeSizeMb: 1.525,
    previewPaidSizeMb: 4.88,
    originalKey: 'op-006/originals/photo-003.jpg',
    previewFreeKey: 'op-006/free/photo-003-low.jpg',
    previewPaidKey: 'op-006/paid/photo-003-hd.jpg',
    sourceLabel: '수업일지 사진',
    createdAt: daysAgo(1),
  },
  {
    id: 'media-004',
    operatorId: 'op-009',
    journalId: null,
    classId: null,
    studentId: null,
    visibility: 'class_all',
    status: 'processing',
    originalInputSizeMb: 52.4,
    previewFreeSizeMb: 0,
    previewPaidSizeMb: 0,
    originalKey: 'op-009/originals/event-video-001.mp4',
    previewFreeKey: null,
    previewPaidKey: null,
    sourceLabel: '이벤트 영상 (처리중)',
    createdAt: daysAgo(0),
  },
]
