// seed/operators.ts — 운영자 시드 데이터 (최소 12개 이상, 상태 골고루)

import type { Operator } from '../domain/types'

const now = () => new Date().toISOString()
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString()
const daysLater = (d: number) => new Date(Date.now() + d * 86400000).toISOString()

export const SEED_OPERATORS: Operator[] = [
  // 1. 자동 승인 운영 중 — 수영장 (회원가입 시 자동 승인)
  {
    id: 'op-001',
    code: 'SW-001',
    name: '송파수영아카데미',
    type: 'swimming_pool',
    representativeName: '김민준',
    phone: '010-2345-6789',
    email: 'min@songpa-swim.co.kr',
    address: '서울시 송파구 올림픽로 135',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    lastLoginAt: daysAgo(1),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 0,
    pausedMemberCount: 0,
    withdrawnMemberCount: 0,
    activeMemberCount: 0,
    currentPlanId: 'plan-free10',
    currentPlanName: '무료',
    billingStatus: 'trial',
    nextBillingAt: null,
    lastPaymentAt: null,
    lastPaymentStatus: 'pending',
    paymentFailCount: 0,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 0,
    storageTotalMb: 512,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 0,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: false,
    policyPrivacyRead: false,
    policyTermsAgreed: false,
    policyLastConfirmedAt: null,
    policyVersionRefund: null,
    policyVersionPrivacy: null,
    policyVersionTerms: null,
    riskLevel: 'low',
    riskFlags: ['정책미확인'],
    authorityStructure: 'single',
    memo: '',
  },

  // 2. 활성 + 유료100 + 정상
  {
    id: 'op-002',
    code: 'SW-002',
    name: '한강수영클럽',
    type: 'swimming_pool',
    representativeName: '이수진',
    phone: '010-3456-7890',
    email: 'sujin@hangang-swim.kr',
    address: '서울시 마포구 월드컵북로 396',
    createdAt: daysAgo(180),
    updatedAt: daysAgo(3),
    lastLoginAt: daysAgo(0),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 87,
    pausedMemberCount: 5,
    withdrawnMemberCount: 12,
    activeMemberCount: 92,
    currentPlanId: 'plan-pro100',
    currentPlanName: '유료100',
    billingStatus: 'active',
    nextBillingAt: daysLater(11),
    lastPaymentAt: daysAgo(19),
    lastPaymentStatus: 'success',
    paymentFailCount: 0,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 7168,
    storageTotalMb: 10240,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 120,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(180),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'low',
    riskFlags: [],
    authorityStructure: 'single',
    memo: '',
  },

  // 3. 결제 실패
  {
    id: 'op-003',
    code: 'SW-003',
    name: '강남아쿠아스쿨',
    type: 'swimming_pool',
    representativeName: '박지훈',
    phone: '010-4567-8901',
    email: 'jihun@gangnam-aqua.kr',
    address: '서울시 강남구 테헤란로 521',
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
    lastLoginAt: daysAgo(3),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 256,
    pausedMemberCount: 18,
    withdrawnMemberCount: 34,
    activeMemberCount: 274,
    currentPlanId: 'plan-pro300',
    currentPlanName: '유료300',
    billingStatus: 'payment_failed',
    nextBillingAt: daysAgo(2),
    lastPaymentAt: daysAgo(32),
    lastPaymentStatus: 'failed',
    paymentFailCount: 2,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 22528,
    storageTotalMb: 30720,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 340,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(365),
    policyVersionRefund: 'v1.0',
    policyVersionPrivacy: 'v1.5',
    policyVersionTerms: 'v1.2',
    riskLevel: 'high',
    riskFlags: ['결제실패', '정책구버전'],
    authorityStructure: 'multi',
    memo: '카드 만료로 결제 실패. 연락 시도 중.',
  },

  // 4. Grace 기간
  {
    id: 'op-004',
    code: 'SW-004',
    name: '분당스포츠센터',
    type: 'franchise',
    representativeName: '최영희',
    phone: '010-5678-9012',
    email: 'yhchoi@bundang-sports.co.kr',
    address: '경기도 성남시 분당구 불정로 90',
    createdAt: daysAgo(420),
    updatedAt: daysAgo(5),
    lastLoginAt: daysAgo(5),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 480,
    pausedMemberCount: 22,
    withdrawnMemberCount: 68,
    activeMemberCount: 502,
    currentPlanId: 'plan-pro500',
    currentPlanName: '유료500',
    billingStatus: 'grace',
    nextBillingAt: daysAgo(5),
    lastPaymentAt: daysAgo(35),
    lastPaymentStatus: 'failed',
    paymentFailCount: 1,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 38912,
    storageTotalMb: 51200,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 280,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(420),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'medium',
    riskFlags: ['grace기간'],
    authorityStructure: 'franchise',
    memo: 'Grace 7일 적용. 결제 카드 교체 중.',
  },

  // 5. 읽기전용 (해지)
  {
    id: 'op-005',
    code: 'SW-005',
    name: '인천수영학원',
    type: 'swimming_pool',
    representativeName: '장동현',
    phone: '010-6789-0123',
    email: 'dh@incheon-swim.kr',
    address: '인천시 남동구 구월로 110',
    createdAt: daysAgo(730),
    updatedAt: daysAgo(3),
    lastLoginAt: daysAgo(3),
    status: 'readonly',
    isApproved: true,
    isReadOnly: true,
    isUploadBlocked: true,
    isDeletionDeferred: false,
    normalMemberCount: 68,
    pausedMemberCount: 8,
    withdrawnMemberCount: 90,
    activeMemberCount: 76,
    currentPlanId: 'plan-pro100',
    currentPlanName: '유료100',
    billingStatus: 'cancelled',
    nextBillingAt: null,
    lastPaymentAt: daysAgo(33),
    lastPaymentStatus: 'refunded',
    paymentFailCount: 0,
    creditBalance: 5000,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: true,
    storageUsedMb: 8704,
    storageTotalMb: 10240,
    storageWarning80: true,
    storageBlocked95: false,
    uploadGrowth7dMb: 0,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: daysLater(21),
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(730),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'medium',
    riskFlags: ['해지', '크레딧보유', '자동삭제예정'],
    authorityStructure: 'single',
    memo: '해지 후 읽기전용. 크레딧 환불 검토 필요.',
  },

  // 6. 저장 95% 차단
  {
    id: 'op-006',
    code: 'SW-006',
    name: '부산마린수영클럽',
    type: 'swimming_pool',
    representativeName: '윤서현',
    phone: '010-7890-1234',
    email: 'sh@busan-marine.kr',
    address: '부산시 해운대구 해운대해변로 264',
    createdAt: daysAgo(550),
    updatedAt: daysAgo(0),
    lastLoginAt: daysAgo(0),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: true,
    isDeletionDeferred: false,
    normalMemberCount: 294,
    pausedMemberCount: 12,
    withdrawnMemberCount: 28,
    activeMemberCount: 306,
    currentPlanId: 'plan-pro300',
    currentPlanName: '유료300',
    billingStatus: 'active',
    nextBillingAt: daysLater(8),
    lastPaymentAt: daysAgo(22),
    lastPaymentStatus: 'success',
    paymentFailCount: 0,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 29491,
    storageTotalMb: 30720,
    storageWarning80: true,
    storageBlocked95: true,
    uploadGrowth7dMb: 1200,
    uploadSpikeFlag: true,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(550),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'critical',
    riskFlags: ['저장95차단', '업로드급증', '업로드차단'],
    authorityStructure: 'multi',
    memo: '업로드 급증으로 95% 초과. 추가 용량 권유.',
  },

  // 7. 저장 80% 경고
  {
    id: 'op-007',
    code: 'SW-007',
    name: '대전아쿠아클럽',
    type: 'rental_team',
    representativeName: '오민혁',
    phone: '010-8901-2345',
    email: 'mh@daejeon-aqua.kr',
    address: '대전시 서구 한밭대로 721',
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
    lastLoginAt: daysAgo(1),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 134,
    pausedMemberCount: 9,
    withdrawnMemberCount: 15,
    activeMemberCount: 143,
    currentPlanId: 'plan-pro300',
    currentPlanName: '유료300',
    billingStatus: 'active',
    nextBillingAt: daysLater(14),
    lastPaymentAt: daysAgo(16),
    lastPaymentStatus: 'success',
    paymentFailCount: 0,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 25190,
    storageTotalMb: 30720,
    storageWarning80: true,
    storageBlocked95: false,
    uploadGrowth7dMb: 450,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(300),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'medium',
    riskFlags: ['저장80경고'],
    authorityStructure: 'single',
    memo: '용량 업그레이드 권유 문자 발송 완료.',
  },

  // 8. 정책 미확인
  {
    id: 'op-008',
    code: 'SW-008',
    name: '광주수영교실',
    type: 'solo_coach',
    representativeName: '정하늘',
    phone: '010-9012-3456',
    email: 'haneul@gwangju-swim.kr',
    address: '광주시 북구 용봉로 77',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(10),
    lastLoginAt: daysAgo(7),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 8,
    pausedMemberCount: 1,
    withdrawnMemberCount: 0,
    activeMemberCount: 9,
    currentPlanId: 'plan-free10',
    currentPlanName: '무료',
    billingStatus: 'trial',
    nextBillingAt: null,
    lastPaymentAt: null,
    lastPaymentStatus: 'pending',
    paymentFailCount: 0,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 102,
    storageTotalMb: 512,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 20,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: false,
    policyPrivacyRead: false,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(30),
    policyVersionRefund: null,
    policyVersionPrivacy: null,
    policyVersionTerms: 'v1.5',
    riskLevel: 'medium',
    riskFlags: ['정책미확인'],
    authorityStructure: 'solo',
    memo: '1인 코치. 정책 문서 미확인 알림 발송 필요.',
  },

  // 9. 업로드 급증 + 크레딧 보유
  {
    id: 'op-009',
    code: 'SW-009',
    name: '수원레저수영장',
    type: 'swimming_pool',
    representativeName: '한지영',
    phone: '010-0123-4567',
    email: 'jy@suwon-leisure.kr',
    address: '경기도 수원시 영통구 광교호수로 200',
    createdAt: daysAgo(240),
    updatedAt: daysAgo(1),
    lastLoginAt: daysAgo(0),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 188,
    pausedMemberCount: 14,
    withdrawnMemberCount: 22,
    activeMemberCount: 202,
    currentPlanId: 'plan-pro300',
    currentPlanName: '유료300',
    billingStatus: 'active',
    nextBillingAt: daysLater(5),
    lastPaymentAt: daysAgo(25),
    lastPaymentStatus: 'success',
    paymentFailCount: 0,
    creditBalance: 10000,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 18944,
    storageTotalMb: 30720,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 820,
    uploadSpikeFlag: true,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(240),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'medium',
    riskFlags: ['업로드급증', '크레딧보유'],
    authorityStructure: 'multi',
    memo: '이벤트 사진 대량 업로드. 크레딧 10,000원 적립.',
  },

  // 10. 자동삭제 예정 (24h)
  {
    id: 'op-010',
    code: 'SW-010',
    name: '울산마스터즈',
    type: 'swimming_pool',
    representativeName: '임성훈',
    phone: '010-1234-5670',
    email: 'sh@ulsan-masters.kr',
    address: '울산시 남구 삼산로 174',
    createdAt: daysAgo(600),
    updatedAt: daysAgo(0),
    lastLoginAt: daysAgo(2),
    status: 'readonly',
    isApproved: true,
    isReadOnly: true,
    isUploadBlocked: true,
    isDeletionDeferred: false,
    normalMemberCount: 45,
    pausedMemberCount: 5,
    withdrawnMemberCount: 88,
    activeMemberCount: 50,
    currentPlanId: 'plan-pro100',
    currentPlanName: '유료100',
    billingStatus: 'auto_delete_scheduled',
    nextBillingAt: null,
    lastPaymentAt: daysAgo(35),
    lastPaymentStatus: 'failed',
    paymentFailCount: 3,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: true,
    refundRepeatFlag: true,
    churnRepeatFlag: false,
    storageUsedMb: 9830,
    storageTotalMb: 10240,
    storageWarning80: true,
    storageBlocked95: true,
    uploadGrowth7dMb: 0,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: daysLater(1),
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(600),
    policyVersionRefund: 'v1.0',
    policyVersionPrivacy: 'v1.5',
    policyVersionTerms: 'v1.2',
    riskLevel: 'critical',
    riskFlags: ['자동삭제24h', '결제실패반복', '분쟁대응'],
    authorityStructure: 'single',
    memo: '24시간 내 자동삭제 예정. 데이터 백업 완료.',
  },

  // 11. Enterprise + 프랜차이즈
  {
    id: 'op-011',
    code: 'SW-011',
    name: '스포츠플러스 프랜차이즈',
    type: 'franchise',
    representativeName: '신대건',
    phone: '010-2345-6780',
    email: 'dkshin@sportsplus.co.kr',
    address: '서울시 강서구 공항대로 291',
    createdAt: daysAgo(900),
    updatedAt: daysAgo(0),
    lastLoginAt: daysAgo(0),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 870,
    pausedMemberCount: 45,
    withdrawnMemberCount: 120,
    activeMemberCount: 915,
    currentPlanId: 'plan-enterprise',
    currentPlanName: '엔터프라이즈',
    billingStatus: 'active',
    nextBillingAt: daysLater(15),
    lastPaymentAt: daysAgo(15),
    lastPaymentStatus: 'success',
    paymentFailCount: 0,
    creditBalance: 50000,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 65536,
    storageTotalMb: 204800,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 380,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(900),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'low',
    riskFlags: [],
    authorityStructure: 'franchise',
    memo: '직영 8개 지점. 전담 매니저 배정.',
  },

  // 12. 제한 (restricted)
  {
    id: 'op-012',
    code: 'SW-012',
    name: '제주오션수영장',
    type: 'swimming_pool',
    representativeName: '고유진',
    phone: '010-3456-7801',
    email: 'yj@jeju-ocean.kr',
    address: '제주시 연동 311-2',
    createdAt: daysAgo(200),
    updatedAt: daysAgo(7),
    lastLoginAt: daysAgo(8),
    status: 'restricted',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: true,
    isDeletionDeferred: false,
    normalMemberCount: 62,
    pausedMemberCount: 3,
    withdrawnMemberCount: 10,
    activeMemberCount: 65,
    currentPlanId: 'plan-pro100',
    currentPlanName: '유료100',
    billingStatus: 'payment_failed',
    nextBillingAt: daysAgo(7),
    lastPaymentAt: daysAgo(37),
    lastPaymentStatus: 'failed',
    paymentFailCount: 2,
    creditBalance: 0,
    hasChargeback: true,
    hasRefundDispute: true,
    refundRepeatFlag: true,
    churnRepeatFlag: false,
    storageUsedMb: 6553,
    storageTotalMb: 10240,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 0,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: false,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(200),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: null,
    policyVersionTerms: 'v1.5',
    riskLevel: 'high',
    riskFlags: ['결제실패', '차지백', '분쟁대응', '반복환불', '정책미확인'],
    authorityStructure: 'single',
    memo: '차지백 발생. 분쟁 대응 중. 업로드 차단 조치.',
  },

  // 13. 승인 대기 (solo_coach)
  {
    id: 'op-013',
    code: 'SW-013',
    name: '이준호 수영코치',
    type: 'solo_coach',
    representativeName: '이준호',
    phone: '010-4567-8902',
    email: 'junho@coach.kr',
    address: '경기도 고양시 일산동구 백석동',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    lastLoginAt: null,
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 0,
    pausedMemberCount: 0,
    withdrawnMemberCount: 0,
    activeMemberCount: 0,
    currentPlanId: 'plan-free10',
    currentPlanName: '무료',
    billingStatus: 'trial',
    nextBillingAt: null,
    lastPaymentAt: null,
    lastPaymentStatus: 'pending',
    paymentFailCount: 0,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 0,
    storageTotalMb: 512,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 0,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(1),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'low',
    riskFlags: [],
    authorityStructure: 'solo',
    memo: '',
  },

  // 14. 이번 주 신규 + 무료 + 활성회원 초과 위험
  {
    id: 'op-014',
    code: 'SW-014',
    name: '청주수영교실',
    type: 'weekend_coach',
    representativeName: '나윤희',
    phone: '010-5678-9013',
    email: 'yh@cheongju-swim.kr',
    address: '충청북도 청주시 흥덕구 옥산면',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(0),
    lastLoginAt: daysAgo(0),
    status: 'active',
    isApproved: true,
    isReadOnly: false,
    isUploadBlocked: false,
    isDeletionDeferred: false,
    normalMemberCount: 9,
    pausedMemberCount: 1,
    withdrawnMemberCount: 0,
    activeMemberCount: 10,
    currentPlanId: 'plan-free10',
    currentPlanName: '무료',
    billingStatus: 'trial',
    nextBillingAt: null,
    lastPaymentAt: null,
    lastPaymentStatus: 'pending',
    paymentFailCount: 0,
    creditBalance: 0,
    hasChargeback: false,
    hasRefundDispute: false,
    refundRepeatFlag: false,
    churnRepeatFlag: false,
    storageUsedMb: 88,
    storageTotalMb: 512,
    storageWarning80: false,
    storageBlocked95: false,
    uploadGrowth7dMb: 55,
    uploadSpikeFlag: false,
    autoDeleteScheduledAt: null,
    policyRefundRead: true,
    policyPrivacyRead: true,
    policyTermsAgreed: true,
    policyLastConfirmedAt: daysAgo(5),
    policyVersionRefund: 'v1.2',
    policyVersionPrivacy: 'v2.0',
    policyVersionTerms: 'v1.5',
    riskLevel: 'low',
    riskFlags: ['무료한도근접'],
    authorityStructure: 'solo',
    memo: '무료 회원 한도(10명) 달성. 유료 전환 유도 필요.',
  },
]
