// seed/subscriptions.ts — 구독·결제 이력 시드

import type { BillingRecord } from '../domain/types'

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString()
const daysLater = (d: number) => new Date(Date.now() + d * 86400000).toISOString()

export const SEED_BILLING_RECORDS: BillingRecord[] = [
  {
    id: 'bill-001',
    operatorId: 'op-002',
    operatorName: '한강수영클럽',
    planId: 'plan-pro100',
    planName: '유료100',
    amount: 5000,
    status: 'success',
    billingStatus: 'active',
    billedAt: daysAgo(19),
    nextBillingAt: daysLater(11),
    failReason: null,
    creditUsed: 0,
    memo: '',
  },
  {
    id: 'bill-002',
    operatorId: 'op-003',
    operatorName: '강남아쿠아스쿨',
    planId: 'plan-pro300',
    planName: '유료300',
    amount: 10000,
    status: 'failed',
    billingStatus: 'payment_failed',
    billedAt: daysAgo(32),
    nextBillingAt: daysAgo(2),
    failReason: '카드 만료',
    creditUsed: 0,
    memo: '2회 실패. 카드 변경 요청 발송.',
  },
  {
    id: 'bill-003',
    operatorId: 'op-004',
    operatorName: '분당스포츠센터',
    planId: 'plan-pro500',
    planName: '유료500',
    amount: 16000,
    status: 'failed',
    billingStatus: 'grace',
    billedAt: daysAgo(35),
    nextBillingAt: daysAgo(5),
    failReason: '카드 잔액 부족',
    creditUsed: 0,
    memo: 'Grace 7일 적용 중.',
  },
  {
    id: 'bill-004',
    operatorId: 'op-005',
    operatorName: '인천수영학원',
    planId: 'plan-pro100',
    planName: '유료100',
    amount: 0,
    status: 'refunded',
    billingStatus: 'cancelled',
    billedAt: daysAgo(33),
    nextBillingAt: null,
    failReason: null,
    creditUsed: 0,
    memo: '구독 해지. 크레딧 5,000원 적립.',
  },
  {
    id: 'bill-005',
    operatorId: 'op-006',
    operatorName: '부산마린수영클럽',
    planId: 'plan-pro300',
    planName: '유료300',
    amount: 10000,
    status: 'success',
    billingStatus: 'active',
    billedAt: daysAgo(22),
    nextBillingAt: daysLater(8),
    failReason: null,
    creditUsed: 0,
    memo: '',
  },
  {
    id: 'bill-006',
    operatorId: 'op-009',
    operatorName: '수원레저수영장',
    planId: 'plan-pro300',
    planName: '유료300',
    amount: 10000,
    status: 'success',
    billingStatus: 'active',
    billedAt: daysAgo(25),
    nextBillingAt: daysLater(5),
    failReason: null,
    creditUsed: 10000,
    memo: '크레딧 10,000원 적용으로 실 결제 0원.',
  },
  {
    id: 'bill-007',
    operatorId: 'op-010',
    operatorName: '울산마스터즈',
    planId: 'plan-pro100',
    planName: '유료100',
    amount: 5000,
    status: 'failed',
    billingStatus: 'auto_delete_scheduled',
    billedAt: daysAgo(35),
    nextBillingAt: null,
    failReason: '반복 결제 실패',
    creditUsed: 0,
    memo: '3회 실패. Grace 만료. 자동삭제 예약.',
  },
  {
    id: 'bill-008',
    operatorId: 'op-011',
    operatorName: '스포츠플러스 프랜차이즈',
    planId: 'plan-enterprise',
    planName: '엔터프라이즈',
    amount: 0,
    status: 'success',
    billingStatus: 'active',
    billedAt: daysAgo(15),
    nextBillingAt: daysLater(15),
    failReason: null,
    creditUsed: 0,
    memo: '별도 계약. 월 인보이스 발행.',
  },
  {
    id: 'bill-009',
    operatorId: 'op-012',
    operatorName: '제주오션수영장',
    planId: 'plan-pro100',
    planName: '유료100',
    amount: 5000,
    status: 'disputed',
    billingStatus: 'payment_failed',
    billedAt: daysAgo(37),
    nextBillingAt: daysAgo(7),
    failReason: '차지백 발생',
    creditUsed: 0,
    memo: '차지백 분쟁 처리 중.',
  },
  {
    id: 'bill-010',
    operatorId: 'op-007',
    operatorName: '대전아쿠아클럽',
    planId: 'plan-pro300',
    planName: '유료300',
    amount: 10000,
    status: 'success',
    billingStatus: 'active',
    billedAt: daysAgo(16),
    nextBillingAt: daysLater(14),
    failReason: null,
    creditUsed: 0,
    memo: '유료100→유료300 업그레이드 후 첫 결제.',
  },
]
