// seed/supportTickets.ts — 고객센터 티켓 시드 (최소 15개)

import type { SupportTicket } from '../domain/types'
import { SLA_HOURS } from '../domain/policies'

const daysAgo = (d: number, h = 0) =>
  new Date(Date.now() - d * 86400000 - h * 3600000).toISOString()
const daysLater = (d: number) => new Date(Date.now() + d * 86400000).toISOString()

function slaDeadline(createdAt: string, type: string) {
  const hours = SLA_HOURS[type] ?? 72
  return new Date(new Date(createdAt).getTime() + hours * 3600000).toISOString()
}
function isOverdue(slaDueAt: string | null, status: string) {
  if (!slaDueAt || status === 'resolved') return false
  return new Date(slaDueAt).getTime() < Date.now()
}

const t1At = daysAgo(0, 2)
const t2At = daysAgo(1, 4)
const t3At = daysAgo(2)
const t4At = daysAgo(3)
const t5At = daysAgo(3, 5)
const t6At = daysAgo(4)
const t7At = daysAgo(5)
const t8At = daysAgo(6)
const t9At = daysAgo(7)
const t10At = daysAgo(8)
const t11At = daysAgo(10)
const t12At = daysAgo(12)
const t13At = daysAgo(14)
const t14At = daysAgo(20)
const t15At = daysAgo(25)
const t16At = daysAgo(0, 1)

export const SEED_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tkt-001',
    requesterName: '박지훈',
    requesterRole: 'operator',
    operatorId: 'op-003',
    operatorName: '강남아쿠아스쿨',
    type: 'payment',
    status: 'in_progress',
    createdAt: t2At,
    lastAnsweredAt: daysAgo(0, 12),
    slaDueAt: slaDeadline(t2At, 'payment'),
    isSlaOverdue: isOverdue(slaDeadline(t2At, 'payment'), 'in_progress'),
    riskLevel: 'high',
    title: '결제 카드 만료로 자동결제 실패 — 카드 변경 방법 문의',
    body: '이번 달 자동결제가 실패했습니다. 카드를 변경하고 싶은데 방법을 알려주세요.',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: 'Grace 7일 적용 완료. 카드 변경 링크 발송 예정.',
  },
  {
    id: 'tkt-002',
    requesterName: '최영희',
    requesterRole: 'operator',
    operatorId: 'op-004',
    operatorName: '분당스포츠센터',
    type: 'payment',
    status: 'in_progress',
    createdAt: t3At,
    lastAnsweredAt: daysAgo(1),
    slaDueAt: slaDeadline(t3At, 'payment'),
    isSlaOverdue: isOverdue(slaDeadline(t3At, 'payment'), 'in_progress'),
    riskLevel: 'high',
    title: 'Grace 기간 중 결제 처리 문의',
    body: '결제 Grace 기간이 언제 끝나는지, 그 전에 카드를 바꾸면 자동결제가 되는지요.',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: 'Grace 만료일 2026-03-26. 카드 변경 가이드 발송.',
  },
  {
    id: 'tkt-003',
    requesterName: '고유진',
    requesterRole: 'operator',
    operatorId: 'op-012',
    operatorName: '제주오션수영장',
    type: 'dispute',
    status: 'escalated_to_tech',
    createdAt: t4At,
    lastAnsweredAt: daysAgo(0, 8),
    slaDueAt: slaDeadline(t4At, 'dispute'),
    isSlaOverdue: isOverdue(slaDeadline(t4At, 'dispute'), 'escalated_to_tech'),
    riskLevel: 'critical',
    title: '카드사 차지백 발생 — 분쟁 대응 요청',
    body: '카드사에서 차지백 처리했다는 연락을 받았습니다. 이유를 모르겠으며 복구를 원합니다.',
    assigneeName: '기술팀',
    repeatedIssueFlag: true,
    internalMemo: '차지백 3회 반복. 계정 제한 조치 병행. 기술팀 전달.',
  },
  {
    id: 'tkt-004',
    requesterName: '윤서현',
    requesterRole: 'operator',
    operatorId: 'op-006',
    operatorName: '부산마린수영클럽',
    type: 'upload_error',
    status: 'escalated_to_tech',
    createdAt: t4At,
    lastAnsweredAt: daysAgo(0, 5),
    slaDueAt: slaDeadline(t4At, 'upload_error'),
    isSlaOverdue: isOverdue(slaDeadline(t4At, 'upload_error'), 'escalated_to_tech'),
    riskLevel: 'high',
    title: '사진 업로드 후 계속 오류 메시지 발생',
    body: '업로드하면 처리 중 표시 후 실패 오류가 납니다. 용량은 90% 이상입니다.',
    assigneeName: '기술팀',
    repeatedIssueFlag: true,
    internalMemo: '저장 95% 초과로 업로드 차단됨. 운영자에게 고지 완료. 기술팀 업로드 로직 확인 중.',
  },
  {
    id: 'tkt-005',
    requesterName: '장동현',
    requesterRole: 'operator',
    operatorId: 'op-005',
    operatorName: '인천수영학원',
    type: 'refund',
    status: 'refund_linked',
    createdAt: t5At,
    lastAnsweredAt: daysAgo(2),
    slaDueAt: slaDeadline(t5At, 'refund'),
    isSlaOverdue: isOverdue(slaDeadline(t5At, 'refund'), 'refund_linked'),
    riskLevel: 'medium',
    title: '해지 후 크레딧 환불 가능 여부 문의',
    body: '해지했는데 남아 있는 크레딧 5,000원 환불이 가능한지 문의드립니다.',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: '정책상 크레딧 환불 가능. 환불 처리 검토 중.',
  },
  {
    id: 'tkt-006',
    requesterName: '임나연',
    requesterRole: 'teacher',
    operatorId: 'op-002',
    operatorName: '한강수영클럽',
    type: 'login_permission',
    status: 'resolved',
    createdAt: t6At,
    lastAnsweredAt: daysAgo(3),
    slaDueAt: slaDeadline(t6At, 'login_permission'),
    isSlaOverdue: false,
    riskLevel: 'low',
    title: '선생님 계정 로그인이 안 됩니다',
    body: '비밀번호 재설정 후에도 로그인이 안 됩니다.',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: '계정 잠금 해제 완료. 임시 비밀번호 발급.',
  },
  {
    id: 'tkt-007',
    requesterName: '오민혁',
    requesterRole: 'operator',
    operatorId: 'op-007',
    operatorName: '대전아쿠아클럽',
    type: 'policy',
    status: 'policy_sent',
    createdAt: t7At,
    lastAnsweredAt: daysAgo(4),
    slaDueAt: slaDeadline(t7At, 'policy'),
    isSlaOverdue: false,
    riskLevel: 'low',
    title: '저장공간 80% 경고 해제 방법 문의',
    body: '80% 경고가 계속 뜨는데 어떻게 해야 용량을 늘릴 수 있나요?',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: '플랜 업그레이드 또는 추가 용량 구매 안내 발송.',
  },
  {
    id: 'tkt-008',
    requesterName: '정하늘',
    requesterRole: 'operator',
    operatorId: 'op-008',
    operatorName: '광주수영교실',
    type: 'policy',
    status: 'received',
    createdAt: t8At,
    lastAnsweredAt: null,
    slaDueAt: slaDeadline(t8At, 'policy'),
    isSlaOverdue: isOverdue(slaDeadline(t8At, 'policy'), 'received'),
    riskLevel: 'low',
    title: '환불 정책 및 개인정보 처리방침 읽는 방법',
    body: '앱에서 정책 문서를 어디서 확인하면 되나요?',
    assigneeName: '',
    repeatedIssueFlag: false,
    internalMemo: '',
  },
  {
    id: 'tkt-009',
    requesterName: '김부모',
    requesterRole: 'parent',
    operatorId: 'op-002',
    operatorName: '한강수영클럽',
    type: 'account',
    status: 'resolved',
    createdAt: t9At,
    lastAnsweredAt: daysAgo(6),
    slaDueAt: slaDeadline(t9At, 'account'),
    isSlaOverdue: false,
    riskLevel: 'low',
    title: '학부모 앱 로그인 오류',
    body: '새 폰으로 바꿨는데 학부모 앱에 로그인이 안 됩니다.',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: '기기 재등록 처리 완료.',
  },
  {
    id: 'tkt-010',
    requesterName: '임성훈',
    requesterRole: 'operator',
    operatorId: 'op-010',
    operatorName: '울산마스터즈',
    type: 'data_delete',
    status: 'need_recheck',
    createdAt: t10At,
    lastAnsweredAt: daysAgo(0, 4),
    slaDueAt: slaDeadline(t10At, 'data_delete'),
    isSlaOverdue: isOverdue(slaDeadline(t10At, 'data_delete'), 'need_recheck'),
    riskLevel: 'critical',
    title: '24시간 내 자동삭제 취소 가능한지 문의',
    body: '해지 처리가 됐는데 사진이 24시간 후 삭제된다고 하는데 취소할 수 있나요?',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: '정책상 해지 후 24h 삭제 불가역. 재구독 시 삭제 유예 가능 안내.',
  },
  {
    id: 'tkt-011',
    requesterName: '선생박',
    requesterRole: 'teacher',
    operatorId: 'op-003',
    operatorName: '강남아쿠아스쿨',
    type: 'app_bug',
    status: 'in_progress',
    createdAt: t11At,
    lastAnsweredAt: daysAgo(5),
    slaDueAt: slaDeadline(t11At, 'app_bug'),
    isSlaOverdue: isOverdue(slaDeadline(t11At, 'app_bug'), 'in_progress'),
    riskLevel: 'medium',
    title: '수업일지 저장 버튼이 가끔 반응하지 않음',
    body: '수업일지 작성 후 저장 버튼을 눌러도 저장이 안 될 때가 있습니다.',
    assigneeName: '기술팀',
    repeatedIssueFlag: true,
    internalMemo: '버그 재현 확인됨. 키보드 겹침 이슈. 다음 릴리즈에서 수정 예정.',
  },
  {
    id: 'tkt-012',
    requesterName: '신대건',
    requesterRole: 'operator',
    operatorId: 'op-011',
    operatorName: '스포츠플러스 프랜차이즈',
    type: 'account',
    status: 'resolved',
    createdAt: t12At,
    lastAnsweredAt: daysAgo(10),
    slaDueAt: slaDeadline(t12At, 'account'),
    isSlaOverdue: false,
    riskLevel: 'low',
    title: '지점별 계정 권한 구조 변경 요청',
    body: '신규 지점 추가로 계정 구조 변경이 필요합니다.',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: '엔터프라이즈 계약 기준 처리 완료.',
  },
  {
    id: 'tkt-013',
    requesterName: '학부모최',
    requesterRole: 'parent',
    operatorId: 'op-004',
    operatorName: '분당스포츠센터',
    type: 'etc',
    status: 'received',
    createdAt: t13At,
    lastAnsweredAt: null,
    slaDueAt: slaDeadline(t13At, 'etc'),
    isSlaOverdue: isOverdue(slaDeadline(t13At, 'etc'), 'received'),
    riskLevel: 'low',
    title: '자녀 수업 일정 변경 문의',
    body: '자녀의 수업 일정을 변경하고 싶습니다.',
    assigneeName: '',
    repeatedIssueFlag: false,
    internalMemo: '운영자 수준 문의. 운영자에게 전달 안내 필요.',
  },
  {
    id: 'tkt-014',
    requesterName: '한지영',
    requesterRole: 'operator',
    operatorId: 'op-009',
    operatorName: '수원레저수영장',
    type: 'upload_error',
    status: 'on_hold',
    createdAt: t14At,
    lastAnsweredAt: daysAgo(15),
    slaDueAt: slaDeadline(t14At, 'upload_error'),
    isSlaOverdue: isOverdue(slaDeadline(t14At, 'upload_error'), 'on_hold'),
    riskLevel: 'medium',
    title: '업로드 급증 이후 속도 저하 문의',
    body: '이벤트 행사 사진 업로드 후 앱 속도가 느립니다.',
    assigneeName: '슈퍼관리자',
    repeatedIssueFlag: false,
    internalMemo: '업로드 급증 확인. CDN 캐시 정리 후 속도 개선 예정.',
  },
  {
    id: 'tkt-015',
    requesterName: '이준호',
    requesterRole: 'operator',
    operatorId: 'op-013',
    operatorName: '이준호 수영코치',
    type: 'account',
    status: 'received',
    createdAt: t15At,
    lastAnsweredAt: null,
    slaDueAt: slaDeadline(t15At, 'account'),
    isSlaOverdue: isOverdue(slaDeadline(t15At, 'account'), 'received'),
    riskLevel: 'low',
    title: '가입 신청 후 승인 상태 확인 요청',
    body: '가입 신청한 지 며칠 됐는데 아직 승인 연락이 없습니다.',
    assigneeName: '',
    repeatedIssueFlag: false,
    internalMemo: '서류 검토 중. 오늘 처리 예정.',
  },
  {
    id: 'tkt-016',
    requesterName: '윤서현',
    requesterRole: 'operator',
    operatorId: 'op-006',
    operatorName: '부산마린수영클럽',
    type: 'policy',
    status: 'received',
    createdAt: t16At,
    lastAnsweredAt: null,
    slaDueAt: slaDeadline(t16At, 'policy'),
    isSlaOverdue: isOverdue(slaDeadline(t16At, 'policy'), 'received'),
    riskLevel: 'medium',
    title: '저장공간 95% 초과 후 업로드 차단 해제 방법',
    body: '업로드가 차단되었다고 합니다. 어떻게 하면 풀 수 있나요?',
    assigneeName: '',
    repeatedIssueFlag: true,
    internalMemo: '',
  },
  // 복구 문의 — 긴급/비상 최우선 처리
  {
    id: 'tkt-recovery-001',
    requesterName: '이민준',
    requesterRole: 'operator',
    operatorId: 'op-007',
    operatorName: '서울수영아카데미',
    type: 'recovery',
    status: 'received',
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(), // 30분 전
    lastAnsweredAt: null,
    slaDueAt: slaDeadline(new Date(Date.now() - 30 * 60000).toISOString(), 'recovery'),
    isSlaOverdue: false,
    riskLevel: 'critical',
    title: '[긴급] 복구 실패 — 스냅샷 복구 후 회원 데이터 불일치',
    body: '어제 오후 스냅샷 복구를 시도했는데 복구 후 회원 데이터가 이전 상태와 다릅니다. 회원 50명 정보가 누락된 것 같습니다. 즉시 확인 부탁드립니다.\n\n복구 시도 시간: 2026-03-22 14:30\n복구 스냅샷: 서울수영아카데미_스냅샷_2026-03-21_09-00\n실패 사유: 부분 복구 시도 후 데이터 불일치 감지',
    assigneeName: '',
    repeatedIssueFlag: false,
    internalMemo: '',
  },
]
