/**
 * WP-X04 Website Build Package Generator
 *
 * APPROVED structured data + original files → ZIP package
 *
 * Package structure:
 *   SWIMNOTE_X_WEBSITE_PACKAGE_<POOL>_<DATE>.zip
 *   ├── website_spec.md        (human-readable build instruction)
 *   ├── website_data.json      (machine-readable data)
 *   ├── source_manifest.json   (provenance tracking)
 *   ├── original/
 *   │   └── website_profile.docx
 *   ├── branding/
 *   │   └── logo.*  (if exists)
 *   └── images/
 *       ├── 01.*  ...up to 10
 */
import { zipSync } from "fflate";
import { downloadFromR2 } from "./objectStorage.js";
import type { WebsiteStructured } from "./docxParser.js";

export interface PackageFile {
  r2_key: string;
  file_name: string;
  file_type: "website" | "logo" | "photo";
  photo_order?: number;
  photo_category?: string;
}

export interface PackageInput {
  pool_id: number;
  pool_name: string;
  profile_id: string;
  submission_id: string;
  submission_version: number;
  structured: WebsiteStructured;
  files: PackageFile[];
  generated_by_id: number;
  generated_by_name?: string;
  approval_timestamp: string;
}

export interface PackageResult {
  zipBuffer: Buffer;
  packageName: string;
  fileCount: number;
}

// ── Name sanitizer ────────────────────────────────────────────────────────────

function sanitizePoolName(name: string): string {
  return name
    .replace(/[^\w가-힣ㄱ-ㅎㅏ-ㅣ\s-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 40);
}

// ── website_spec.md generator ────────────────────────────────────────────────

function notProvided(val: string | undefined): string {
  return val?.trim() || "[NOT PROVIDED]";
}

function objectToMd(obj: Record<string, string>, indent = ""): string {
  return Object.entries(obj)
    .map(([k, v]) => `${indent}- **${k}**: ${notProvided(v)}`)
    .join("\n");
}

function generateWebsiteSpec(input: PackageInput): string {
  const s = input.structured;
  const d = new Date().toISOString().slice(0, 10);
  const logo = input.files.find(f => f.file_type === "logo");
  const photos = input.files.filter(f => f.file_type === "photo")
    .sort((a, b) => (a.photo_order ?? 0) - (b.photo_order ?? 0));

  return `# SWIMNOTE X WEBSITE BUILD SPECIFICATION
# ${input.pool_name}
# Generated: ${d}
# Package Version: based on submission v${input.submission_version}
# Structured Approval: ${input.approval_timestamp}

---

## POOL NAME
${input.pool_name}

---

## BRAND / SLOGAN
${objectToMd(s.brand)}

---

## BASIC INFO
${objectToMd(s.basic_info)}

---

## HERO
${notProvided(s.brand["hero_message"] || s.brand["한 줄 소개"] || s.brand["슬로건"])}

---

## INTRODUCTION
${notProvided(s.brand["소개글"] || s.brand["수영장 소개"] || s.brand["한 줄 소개"])}

---

## STRENGTHS
${s.strengths.length > 0 ? s.strengths.map((v, i) => `${i + 1}. ${v}`).join("\n") : "[NOT PROVIDED]"}

---

## DIFFERENTIATION
${objectToMd(s.differentiation)}

---

## PHILOSOPHY
${objectToMd(s.philosophy)}

---

## PROGRAMS
${s.programs.length > 0 ? s.programs.map((v, i) => `${i + 1}. ${v}`).join("\n") : "[NOT PROVIDED]"}

---

## LEVEL SYSTEM
${s.level_system.length > 0 ? s.level_system.map((v, i) => `${i + 1}. ${v}`).join("\n") : "[NOT PROVIDED]"}

---

## EDUCATION PROCESS
${objectToMd(s.education_process)}

---

## FACILITIES
${objectToMd(s.facilities)}

---

## SAFETY
${objectToMd(s.safety)}

---

## LOCATION / VEHICLE / PARKING
${objectToMd(s.vehicle_location)}

---

## USAGE INFORMATION
${objectToMd(s.usage_information)}

---

## COACHES
${s.coaches.length > 0 ? s.coaches.map((v, i) => `${i + 1}. ${v}`).join("\n") : "[NOT PROVIDED]"}

---

## TRUST / CREDENTIALS
${objectToMd(s.trust_credentials)}

---

## FAQ
${s.faq.length > 0
  ? s.faq.map((f, i) => `**Q${i + 1}**: ${f.question}\n**A${i + 1}**: ${f.answer}`).join("\n\n")
  : "[NOT PROVIDED]"}

---

## WEBSITE PREFERENCES
${objectToMd(s.website_preferences)}

---

## DO NOT INCLUDE
${s.restricted_information?.trim() || "[NOT PROVIDED]"}

---

## LOGO
${logo ? `logo.${logo.file_name.split(".").pop()}` : "NOT PROVIDED"}

---

## IMAGE MANIFEST
${photos.length > 0
  ? photos.map((p, i) => `${String(i + 1).padStart(2, "0")}. ${p.file_name}${p.photo_category ? ` (${p.photo_category})` : ""}`).join("\n")
  : "[NO IMAGES PROVIDED]"}
Total images: ${photos.length}

---

## FREE NOTES
${s.free_notes?.trim() || "[NOT PROVIDED]"}

---
*Generated by SWIMNOTE — Do not fabricate missing information.*
`;
}

// ── website_data.json generator ───────────────────────────────────────────────

function generateWebsiteData(input: PackageInput): string {
  const logo = input.files.find(f => f.file_type === "logo");
  const photos = input.files.filter(f => f.file_type === "photo")
    .sort((a, b) => (a.photo_order ?? 0) - (b.photo_order ?? 0));

  const data = {
    schema_version: "1.0",
    pool_id: input.pool_id,
    pool_name: input.pool_name,
    generated_at: new Date().toISOString(),
    source_submission_version: input.submission_version,
    structured_approval_at: input.approval_timestamp,
    data: {
      ...input.structured,
      parse_warnings: undefined,
    },
    logo: logo ? { file_name: logo.file_name } : null,
    images: photos.map((p, i) => ({
      order: i + 1,
      file_name: p.file_name,
      category: p.photo_category ?? null,
    })),
  };

  return JSON.stringify(data, null, 2);
}

// ── source_manifest.json generator ───────────────────────────────────────────

function generateManifest(input: PackageInput): string {
  const logo = input.files.find(f => f.file_type === "logo");
  const websiteDoc = input.files.find(f => f.file_type === "website");
  const photos = input.files.filter(f => f.file_type === "photo")
    .sort((a, b) => (a.photo_order ?? 0) - (b.photo_order ?? 0));

  const manifest = {
    pool_id: input.pool_id,
    pool_name: input.pool_name,
    source_submission_id: input.submission_id,
    source_submission_version: input.submission_version,
    template_version: input.structured.template_version,
    structured_profile_id: input.profile_id,
    structured_approval_at: input.approval_timestamp,
    package_generated_at: new Date().toISOString(),
    package_generated_by: input.generated_by_name ?? `user:${input.generated_by_id}`,
    files: {
      website_docx: websiteDoc ? { file_name: websiteDoc.file_name } : null,
      logo: logo ? { file_name: logo.file_name } : null,
      photos: photos.map((p, i) => ({
        order: i + 1,
        file_name: p.file_name,
        category: p.photo_category ?? null,
      })),
    },
  };

  return JSON.stringify(manifest, null, 2);
}

// ── Main package generator ────────────────────────────────────────────────────

export async function generateWebsitePackage(
  input: PackageInput
): Promise<PackageResult> {
  const sanitizedName = sanitizePoolName(input.pool_name);
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const packageName = `SWIMNOTE_X_WEBSITE_PACKAGE_${sanitizedName}_${dateStr}.zip`;

  const zipEntries: Record<string, Uint8Array> = {};

  // Generated text files
  const encoder = (s: string) => new TextEncoder().encode(s);
  zipEntries["website_spec.md"]        = encoder(generateWebsiteSpec(input));
  zipEntries["website_data.json"]      = encoder(generateWebsiteData(input));
  zipEntries["source_manifest.json"]   = encoder(generateManifest(input));

  // Download and include original files from R2
  const logo    = input.files.find(f => f.file_type === "logo");
  const websiteDoc = input.files.find(f => f.file_type === "website");
  const photos  = input.files.filter(f => f.file_type === "photo")
    .sort((a, b) => (a.photo_order ?? 0) - (b.photo_order ?? 0));

  if (websiteDoc) {
    const res = await downloadFromR2(websiteDoc.r2_key, "photo");
    if (res.ok && res.data) {
      const ext = websiteDoc.file_name.split(".").pop() ?? "docx";
      zipEntries[`original/website_profile.${ext}`] = new Uint8Array(res.data);
    }
  }

  if (logo) {
    const res = await downloadFromR2(logo.r2_key, "photo");
    if (res.ok && res.data) {
      const ext = logo.file_name.split(".").pop() ?? "png";
      zipEntries[`branding/logo.${ext}`] = new Uint8Array(res.data);
    }
  }

  for (let i = 0; i < Math.min(photos.length, 10); i++) {
    const photo = photos[i];
    const res = await downloadFromR2(photo.r2_key, "photo");
    if (res.ok && res.data) {
      const ext = photo.file_name.split(".").pop() ?? "jpg";
      const order = String(i + 1).padStart(2, "0");
      zipEntries[`images/${order}.${ext}`] = new Uint8Array(res.data);
    }
  }

  const zipBuffer = Buffer.from(zipSync(zipEntries));

  return {
    zipBuffer,
    packageName,
    fileCount: Object.keys(zipEntries).length,
  };
}
