import { Router, type IRouter } from "express";
import { requireWritable } from "../lib/readonlyGuard.js";
import healthRouter from "./health";
import authRouter from "./auth.js";
import poolsRouter from "./pools.js";
import adminRouter from "./admin.js";
import studentsRouter from "./students.js";
import classGroupsRouter from "./class-groups.js";
import attendanceRouter from "./attendance.js";
import noticesRouter from "./notices.js";
import parentRouter from "./parent.js";
import uploadsRouter from "./uploads.js";
import photosRouter from "./photos.js";
import diaryRouter from "./diary.js";
import notificationsRouter from "./notifications.js";
import teachersRouter from "./teachers.js";
import branchesRouter from "./branches.js";
import membersRouter from "./members.js";
import billingRouter from "./billing.js";
import parentRequestsRouter from "./parent-requests.js";
import teacherInvitesRouter from "./teacher-invites.js";
import classSchedulesRouter from "./class-schedules.js";
import videosRouter from "./videos.js";
import todayScheduleRouter from "./today-schedule.js";
import pushTokenRouter from "./push-token.js";
import messengerRouter from "./messenger.js";
import pricingRouter from "./pricing.js";
import holidaysRouter from "./holidays.js";
import absencesRouter from "./absences.js";
import extraClassesRouter from "./extra-classes.js";
import settlementRouter from "./settlement.js";
import storageRouter from "./storage.js";
import killSwitchRouter from "./kill-switch.js";
import unregisteredRouter from "./unregistered.js";
import superSyncRouter from "./super-sync.js";
import superRouter from "./super.js";
import pushSettingsRouter from "./push-settings.js";
import classChangeLogsRouter from "./class-change-logs.js";
import dbStatusRouter from "./db-status.js";

const router: IRouter = Router();

// 읽기전용 풀 쓰기 차단 (결제 실패 / 삭제 예약 상태)
router.use(requireWritable as any);

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/pools", poolsRouter);
router.use("/admin", adminRouter);
router.use("/students", studentsRouter);
router.use("/class-groups", classGroupsRouter);
router.use("/attendance", attendanceRouter);
router.use("/notices", noticesRouter);
router.use("/parent", parentRouter);
router.use("/uploads", uploadsRouter);
router.use("/", photosRouter);
router.use("/", diaryRouter);
router.use("/", notificationsRouter);
router.use("/", teachersRouter);
router.use("/", videosRouter);
router.use("/members", membersRouter);
router.use("/branches", branchesRouter);
router.use("/billing", billingRouter);
router.use("/", parentRequestsRouter);
router.use("/", teacherInvitesRouter);
router.use("/", classSchedulesRouter);
router.use("/", todayScheduleRouter);
router.use("/", pushTokenRouter);
router.use("/", messengerRouter);
router.use("/", pricingRouter);
router.use("/", holidaysRouter);
router.use("/", absencesRouter);
router.use("/", extraClassesRouter);
router.use("/", settlementRouter);
router.use("/", storageRouter);
router.use("/", killSwitchRouter);
router.use("/", unregisteredRouter);
router.use("/", superSyncRouter);
router.use("/", superRouter);
router.use("/", pushSettingsRouter);
router.use("/class-change-logs", classChangeLogsRouter);
router.use("/super/db-status", dbStatusRouter);

export default router;
