import { Router, type IRouter } from "express";
import aiV1Router from "./ai-v1.js";
import { requireWritable } from "../lib/readonlyGuard.js";
import healthRouter from "./health";
import authRouter from "./auth.js";
import poolsRouter from "./pools.js";
import adminRouter from "./admin.js";
import studentsRouter from "./students.js";
import classGroupsRouter from "./class-groups.js";
import attendanceRouter from "./attendance.js";
import noticesRouter from "./notices.js";
import parentRouter from "./parent.js";
import uploadsRouter from "./uploads.js";
import photosRouter from "./photos.js";
import diaryRouter from "./diary.js";
import notificationsRouter from "./notifications.js";
import teachersRouter from "./teachers.js";
import branchesRouter from "./branches.js";
import membersRouter from "./members.js";
import billingRouter from "./billing.js";
import parentRequestsRouter from "./parent-requests.js";
import teacherInvitesRouter from "./teacher-invites.js";
import classSchedulesRouter from "./class-schedules.js";
import videosRouter from "./videos.js";
import todayScheduleRouter from "./today-schedule.js";
import pushTokenRouter from "./push-token.js";
import messengerRouter from "./messenger.js";
import pricingRouter from "./pricing.js";
import holidaysRouter from "./holidays.js";
import absencesRouter from "./absences.js";
import extraClassesRouter from "./extra-classes.js";
import settlementRouter from "./settlement.js";
import storageRouter from "./storage.js";
import killSwitchRouter from "./kill-switch.js";
import unregisteredRouter from "./unregistered.js";
import privacyPageRouter from "./privacy-page.js";
import superSyncRouter from "./super-sync.js";
import superRouter from "./super.js";
import superAiCostRouter from "./super-ai-cost.js";
import supportTicketsRouter from "./support-tickets.js";
import supportCasesRouter from "./support-cases.js";
import pushSettingsRouter from "./push-settings.js";
import classChangeLogsRouter from "./class-change-logs.js";
import dbStatusRouter from "./db-status.js";
import infraUsageRouter from "./infra-usage.js";
import backupStatusRouter from "./backup-status.js";
import restoreRouter from "./restore.js";
import platformBannersRouter from "./platform-banners.js";
import systemHealthRouter from "./system-health.js";
import crashReportRouter from "./crash-report.js";
import appVersionRouter from "./app-version.js";
import inquiriesRouter from "./inquiries.js";
import aiEngineDocRouter from "./ai-engine-doc.js";
import commentsRouter from "./comments.js";
import aiRouter from "./ai.js";
import storyRouter from "./story.js";
import xGrowthRouter from "./x-growth.js";
import xSetupRouter from "./x-setup.js";
import x04StructuringRouter from "./x04-structuring.js";
import csPa0Router from "./cs-pa0.js";
import superSupportRouter from "./super-support.js";
import frontendMapRouter from "./frontend-map.js";
import knowledgeSearchRouter from "./knowledge-search.js";
import knowledgeApprovalRouter from "./knowledge-approval.js";
import resolutionRouter from "./resolution-router.js";
import supportRespondRouter from "./support-respond.js";
import parentGrowthReportRouter from "./parent-growth-report.js";
import parentCurriculumRouter    from "./parent-curriculum.js";
import teacherGrowthReportReviewRouter from "./teacher-growth-report-review.js";
import publishGrowthReportRouter from "./publish-growth-report.js";
import growthReportInteractionsRouter from "./growth-report-interactions.js";

const router: IRouter = Router();

// 읽기전용 풀 쓰기 차단 (결제 실패 / 삭제 예약 상태)
router.use(requireWritable as any);

// ── Super 라우터 최우선 마운트 (다른 "/" 라우터들이 /super/* 경로를 가로채지 않도록) ──
router.use("/", superSyncRouter);
router.use("/", superRouter);
router.use("/", superAiCostRouter);
router.use("/", superSupportRouter);
router.use("/super/db-status", dbStatusRouter);
router.use("/super/infra-usage", infraUsageRouter);

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/pools", poolsRouter);
router.use("/admin", adminRouter);
router.use("/students", studentsRouter);
router.use("/class-groups", classGroupsRouter);
router.use("/attendance", attendanceRouter);
router.use("/notices", noticesRouter);
router.use("/parent", parentRouter);
router.use("/", parentGrowthReportRouter);
router.use("/", parentCurriculumRouter);
router.use("/", teacherGrowthReportReviewRouter);
router.use("/", publishGrowthReportRouter);
router.use("/", growthReportInteractionsRouter);
router.use("/uploads", uploadsRouter);
router.use("/", photosRouter);
router.use("/", diaryRouter);
router.use("/", notificationsRouter);
router.use("/", teachersRouter);
router.use("/", videosRouter);
router.use("/members", membersRouter);
router.use("/branches", branchesRouter);
router.use("/billing", billingRouter);
router.use("/", parentRequestsRouter);
router.use("/", teacherInvitesRouter);
router.use("/", classSchedulesRouter);
router.use("/", todayScheduleRouter);
router.use("/", pushTokenRouter);
router.use("/", messengerRouter);
router.use("/", pricingRouter);
router.use("/", holidaysRouter);
router.use("/", absencesRouter);
router.use("/", extraClassesRouter);
router.use("/", settlementRouter);
router.use("/", storageRouter);
router.use("/", killSwitchRouter);
router.use("/", unregisteredRouter);
router.use("/", supportTicketsRouter);
router.use("/", supportCasesRouter);
router.use("/", pushSettingsRouter);
router.use("/class-change-logs", classChangeLogsRouter);
router.use("/", backupStatusRouter);
router.use("/", restoreRouter);
router.use("/", privacyPageRouter);
router.use("/", platformBannersRouter);
router.use("/", systemHealthRouter);
router.use("/", crashReportRouter);
router.use("/", appVersionRouter);
router.use("/", inquiriesRouter);
router.use("/", aiEngineDocRouter);
router.use("/", commentsRouter);
router.use("/", aiRouter);
router.use("/", storyRouter);
router.use("/", xGrowthRouter);
router.use("/", xSetupRouter);
router.use("/", x04StructuringRouter);
router.use("/", csPa0Router);
router.use("/", frontendMapRouter);
router.use("/", knowledgeSearchRouter);
router.use("/", knowledgeApprovalRouter);
router.use("/", resolutionRouter);
router.use("/", supportRespondRouter);
router.use("/", aiV1Router);

// CS24: Learning Loop — Knowledge Candidates
import supportLearningRouter from "./support-learning.js";
router.use("/", supportLearningRouter);

// Curriculum APP MASTER Import (super_admin)
import superCurriculumRouter from "./super-curriculum.js";
router.use("/super/curriculum", superCurriculumRouter);

// Multi-Pool Membership API
import membershipsRouter from "./memberships.js";
import terminologyRouter from "./terminology.js";
router.use("/", membershipsRouter);
router.use("/", terminologyRouter);

export default router;
