/**
 * SWIMNOTE Frontend Map Registry — v1
 *
 * 앱 화면 구조를 Support AI가 이해하기 위한 정적 레지스트리.
 * DB 저장 없음. 코드와 함께 버전 관리.
 *
 * frontend_map_version: "1.6.3"
 * 앱 버전 1.6.3 기준 (2026-08-17)
 *
 * 수정 원칙:
 * - 실제 존재하는 화면만 등록
 * - purpose는 광고성 문구 금지 — 실제 기능 기준
 * - common_errors는 코드에 실제 존재하는 오류만
 * - support_keywords는 사용자가 실제로 말할 단어만
 */

export const FRONTEND_MAP_VERSION = "1.6.3";

export type ScreenRole = "pool_admin" | "sub_admin" | "teacher" | "parent" | "super_admin";
export type ScreenMode = "normal" | "x" | "x_pending";
export type ActionType =
  | "NAVIGATE"
  | "SUBMIT"
  | "OPEN_MODAL"
  | "DOWNLOAD"
  | "UPLOAD"
  | "REQUEST"
  | "CALL_API"
  | "OTHER";

export interface ScreenButton {
  id: string;
  label: string;
  action_type: ActionType;
  target_route?: string;
  required_permission?: string;
  notes?: string;
}

export interface ScreenInput {
  field_id: string;
  label: string;
  input_type: "text" | "number" | "date" | "select" | "toggle" | "file" | "phone" | "email";
  required: boolean;
}

export interface FrontendScreen {
  screen_id: string;
  screen_name: string;
  route: string;
  file_path: string;
  available_roles: ScreenRole[];
  available_modes: ScreenMode[];
  purpose: string;
  buttons: ScreenButton[];
  inputs: ScreenInput[];
  permissions: string[];
  feature_flags: string[];
  next_routes: string[];
  previous_routes: string[];
  related_api: string[];
  related_features: string[];
  common_errors: string[];
  known_solutions: string[];
  support_keywords: string[];
  deep_link?: string;
  frontend_map_version: string;
}

const V = FRONTEND_MAP_VERSION;

// ─── AUTH SCREENS ──────────────────────────────────────────────────────────────

const authScreens: FrontendScreen[] = [
  {
    screen_id: "LOGIN",
    screen_name: "로그인",
    route: "/login",
    file_path: "app/(auth)/login.tsx",
    available_roles: ["pool_admin", "sub_admin", "teacher"],
    available_modes: ["normal", "x"],
    purpose: "수영장 관리자 및 강사가 이메일/비밀번호로 로그인하는 화면",
    buttons: [
      { id: "login_submit", label: "로그인", action_type: "SUBMIT" },
      { id: "forgot_pw", label: "비밀번호 찾기", action_type: "NAVIGATE", target_route: "/forgot-password" },
      { id: "signup", label: "회원가입", action_type: "NAVIGATE", target_route: "/signup" },
    ],
    inputs: [
      { field_id: "email", label: "이메일", input_type: "email", required: true },
      { field_id: "password", label: "비밀번호", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: ["/dashboard", "/teacher/today-schedule", "/otp-verify"],
    previous_routes: [],
    related_api: ["/auth/login"],
    related_features: ["인증"],
    common_errors: ["이메일 또는 비밀번호가 올바르지 않습니다", "계정을 찾을 수 없습니다"],
    known_solutions: [],
    support_keywords: ["로그인", "로그인 안됨", "비밀번호", "이메일"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_LOGIN",
    screen_name: "학부모 로그인",
    route: "/parent-login",
    file_path: "app/(auth)/parent-login.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 전화번호 인증 또는 소셜 로그인으로 접속하는 화면",
    buttons: [
      { id: "send_otp", label: "인증번호 전송", action_type: "CALL_API" },
      { id: "kakao_login", label: "카카오로 시작하기", action_type: "CALL_API" },
      { id: "apple_login", label: "Apple로 로그인", action_type: "CALL_API" },
    ],
    inputs: [
      { field_id: "phone", label: "전화번호", input_type: "phone", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: ["/otp-verify", "/parent-onboard-nickname", "/home"],
    previous_routes: [],
    related_api: ["/auth/parent-login", "/auth/send-otp"],
    related_features: ["학부모 인증"],
    common_errors: ["인증번호가 만료되었습니다", "전화번호를 찾을 수 없습니다"],
    known_solutions: [],
    support_keywords: ["학부모 로그인", "문자 인증", "카카오 로그인", "Apple 로그인"],
    frontend_map_version: V,
  },
  {
    screen_id: "SIGNUP",
    screen_name: "회원가입",
    route: "/signup",
    file_path: "app/(auth)/signup.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal"],
    purpose: "수영장 관리자가 이메일·비밀번호·전화번호를 입력해 계정을 생성하는 화면",
    buttons: [
      { id: "signup_submit", label: "가입하기", action_type: "SUBMIT" },
    ],
    inputs: [
      { field_id: "name", label: "이름", input_type: "text", required: true },
      { field_id: "email", label: "이메일", input_type: "email", required: true },
      { field_id: "phone", label: "전화번호", input_type: "phone", required: true },
      { field_id: "password", label: "비밀번호", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: ["/otp-verify", "/pool-apply"],
    previous_routes: ["/login"],
    related_api: ["/auth/signup"],
    related_features: ["인증", "수영장 등록"],
    common_errors: ["이미 사용 중인 이메일입니다", "전화번호 인증 실패"],
    known_solutions: [],
    support_keywords: ["회원가입", "가입", "계정 만들기"],
    frontend_map_version: V,
  },
  {
    screen_id: "FORGOT_PASSWORD",
    screen_name: "비밀번호 찾기",
    route: "/forgot-password",
    file_path: "app/(auth)/forgot-password.tsx",
    available_roles: ["pool_admin", "teacher"],
    available_modes: ["normal", "x"],
    purpose: "이메일로 비밀번호 재설정 링크를 전송하는 화면",
    buttons: [
      { id: "send_reset", label: "재설정 링크 전송", action_type: "CALL_API" },
    ],
    inputs: [
      { field_id: "email", label: "이메일", input_type: "email", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/login"],
    related_api: ["/auth/forgot-password"],
    related_features: ["인증"],
    common_errors: ["등록되지 않은 이메일입니다"],
    known_solutions: [],
    support_keywords: ["비밀번호 잊음", "비밀번호 재설정", "비밀번호 찾기"],
    frontend_map_version: V,
  },
  {
    screen_id: "OTP_VERIFY",
    screen_name: "OTP 인증",
    route: "/otp-verify",
    file_path: "app/(auth)/otp-verify.tsx",
    available_roles: ["pool_admin", "teacher", "parent"],
    available_modes: ["normal", "x"],
    purpose: "SMS로 전송된 인증번호를 입력해 전화번호를 인증하는 화면",
    buttons: [
      { id: "verify", label: "인증 확인", action_type: "SUBMIT" },
      { id: "resend", label: "재전송", action_type: "CALL_API" },
    ],
    inputs: [
      { field_id: "otp", label: "인증번호", input_type: "number", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: ["/dashboard", "/home", "/pool-apply"],
    previous_routes: ["/login", "/parent-login"],
    related_api: ["/auth/verify-otp"],
    related_features: ["인증"],
    common_errors: ["인증번호가 일치하지 않습니다", "인증번호가 만료되었습니다"],
    known_solutions: [],
    support_keywords: ["인증번호", "문자 인증", "OTP", "6자리"],
    frontend_map_version: V,
  },
];

// ─── ADMIN SCREENS ─────────────────────────────────────────────────────────────

const adminScreens: FrontendScreen[] = [
  {
    screen_id: "ADMIN_DASHBOARD",
    screen_name: "관리자 홈",
    route: "/dashboard",
    file_path: "app/(admin)/dashboard.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "핵심 운영 지표 4개(총 학생·오늘 수업·미수납·보강 대기)와 기능 바로가기 아이콘을 표시하는 메인 허브",
    buttons: [
      { id: "students", label: "학생 관리", action_type: "NAVIGATE", target_route: "/members" },
      { id: "schedule", label: "스케줄", action_type: "NAVIGATE", target_route: "/class-hub" },
      { id: "diary", label: "일지", action_type: "NAVIGATE", target_route: "/diary-teacher-entries" },
      { id: "attendance", label: "출결", action_type: "NAVIGATE", target_route: "/attendance" },
      { id: "messenger", label: "메신저", action_type: "NAVIGATE", target_route: "/messenger" },
      { id: "makeups", label: "보강", action_type: "NAVIGATE", target_route: "/makeups" },
      { id: "more", label: "더보기", action_type: "NAVIGATE", target_route: "/more" },
      { id: "x_mode_badge", label: "X 모드 배지", action_type: "NAVIGATE", target_route: "/x-mode-hub", notes: "X 모드 활성 시 표시" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: ["xmode"],
    next_routes: ["/members", "/class-hub", "/diary-teacher-entries", "/attendance", "/messenger", "/makeups", "/more"],
    previous_routes: [],
    related_api: ["/pools/dashboard-stats"],
    related_features: ["대시보드", "X 모드"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["홈", "대시보드", "메인", "지표", "통계"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_MEMBERS",
    screen_name: "학생 관리",
    route: "/members",
    file_path: "app/(admin)/members.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "수영장에 등록된 전체 학생 목록을 조회하고 검색·필터링하는 화면",
    buttons: [
      { id: "add_member", label: "학생 추가", action_type: "NAVIGATE", target_route: "/bulk-register" },
      { id: "member_detail", label: "학생 상세", action_type: "NAVIGATE", target_route: "/member-detail" },
      { id: "invite_qr", label: "초대 QR", action_type: "NAVIGATE", target_route: "/invite-qr" },
    ],
    inputs: [
      { field_id: "search", label: "학생 검색", input_type: "text", required: false },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: ["/member-detail", "/bulk-register", "/invite-qr"],
    previous_routes: ["/dashboard"],
    related_api: ["/members", "/students"],
    related_features: ["학생 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["학생", "학생 목록", "회원", "명단", "학생 찾기"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_MEMBER_DETAIL",
    screen_name: "학생 상세",
    route: "/member-detail",
    file_path: "app/(admin)/member-detail.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "개별 학생의 등록 정보·수업·출결·납부 내역을 조회하고 수정하는 화면",
    buttons: [
      { id: "edit_info", label: "정보 수정", action_type: "OPEN_MODAL" },
      { id: "change_class", label: "반 변경", action_type: "OPEN_MODAL" },
      { id: "attendance_detail", label: "출결 상세", action_type: "NAVIGATE" },
    ],
    inputs: [],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: ["/attendance"],
    previous_routes: ["/members"],
    related_api: ["/members/:id", "/students/:id"],
    related_features: ["학생 관리", "출결"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["학생 정보", "학생 상세", "학생 수정", "반 변경", "출결 기록"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_CLASS_HUB",
    screen_name: "스케줄",
    route: "/class-hub",
    file_path: "app/(admin)/class-hub.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "전체 반의 수업 스케줄을 캘린더 또는 목록으로 조회하는 화면",
    buttons: [
      { id: "add_class", label: "반 추가", action_type: "NAVIGATE", target_route: "/classes" },
      { id: "class_detail", label: "반 상세", action_type: "NAVIGATE", target_route: "/class-management" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/class-management", "/classes", "/attendance"],
    previous_routes: ["/dashboard"],
    related_api: ["/classes", "/schedules"],
    related_features: ["스케줄", "반 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["스케줄", "시간표", "반", "수업 시간", "클래스"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_CLASSES",
    screen_name: "반 목록",
    route: "/classes",
    file_path: "app/(admin)/classes.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "수영장의 전체 반을 목록으로 보고 추가·수정할 수 있는 화면",
    buttons: [
      { id: "add_class", label: "반 추가", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/class-management"],
    previous_routes: ["/class-hub"],
    related_api: ["/classes"],
    related_features: ["반 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["반", "반 목록", "반 추가", "클래스"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_CLASS_MANAGEMENT",
    screen_name: "반 관리",
    route: "/class-management",
    file_path: "app/(admin)/class-management.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "특정 반의 학생 배정·수업 일정·수용 인원을 설정하는 화면",
    buttons: [
      { id: "assign_student", label: "학생 배정", action_type: "OPEN_MODAL" },
      { id: "edit_schedule", label: "스케줄 수정", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/class-capacity-settings"],
    previous_routes: ["/classes"],
    related_api: ["/classes/:id", "/class-members"],
    related_features: ["반 관리", "학생 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["반 관리", "학생 배정", "수업 인원", "반 수정"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_ATTENDANCE",
    screen_name: "출결",
    route: "/attendance",
    file_path: "app/(admin)/attendance.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "날짜별·반별 학생 출결을 조회하고 변경하는 화면",
    buttons: [
      { id: "mark_attendance", label: "출결 체크", action_type: "CALL_API" },
      { id: "date_pick", label: "날짜 선택", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/makeups"],
    previous_routes: ["/dashboard", "/class-hub"],
    related_api: ["/attendance", "/attendance/:date"],
    related_features: ["출결"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["출결", "출석", "결석", "출결 체크", "출결 기록"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_MAKEUPS",
    screen_name: "보강",
    route: "/makeups",
    file_path: "app/(admin)/makeups.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "결석으로 발생한 보강 일정을 조회·처리하는 화면",
    buttons: [
      { id: "approve_makeup", label: "보강 승인", action_type: "CALL_API" },
      { id: "deny_makeup", label: "보강 거절", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/dashboard", "/attendance"],
    related_api: ["/makeups", "/makeups/:id"],
    related_features: ["보강"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["보강", "보강 요청", "보강 승인", "보강 처리"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_DIARY_TEACHER_ENTRIES",
    screen_name: "수업 일지 목록",
    route: "/diary-teacher-entries",
    file_path: "app/(admin)/diary-teacher-entries.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "강사들이 작성한 수업 일지를 날짜·반별로 조회하는 관리자 전용 화면",
    buttons: [
      { id: "write_diary", label: "일지 작성", action_type: "NAVIGATE", target_route: "/diary-write" },
      { id: "filter", label: "필터", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/diary-write"],
    previous_routes: ["/dashboard"],
    related_api: ["/teacher-diary", "/diaries"],
    related_features: ["수업 일지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["일지 목록", "수업 일지", "일지 확인", "강사 일지"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_DIARY_WRITE",
    screen_name: "일지 작성",
    route: "/diary-write",
    file_path: "app/(admin)/diary-write.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "관리자가 특정 날짜·반의 수업 일지를 직접 작성하거나 AI 초안을 생성하는 화면",
    buttons: [
      { id: "ai_generate", label: "AI 초안", action_type: "CALL_API", notes: "X 모드 활성 필요" },
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [
      { field_id: "content", label: "일지 내용", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: ["xmode"],
    next_routes: ["/diary-teacher-entries"],
    previous_routes: ["/diary-teacher-entries"],
    related_api: ["/teacher-diary", "/ai/diary-generate"],
    related_features: ["수업 일지", "AI 일지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["일지 작성", "수업 일지", "AI 일지", "일지 저장"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_DIARY_TEMPLATE_SETTINGS",
    screen_name: "일지 템플릿 설정",
    route: "/diary-template-settings",
    file_path: "app/(admin)/diary-template-settings.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "AI 일지 생성에 사용하는 수업 템플릿을 관리하는 화면",
    buttons: [
      { id: "add_template", label: "템플릿 추가", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: ["xmode"],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/diary-templates"],
    related_features: ["수업 일지", "AI 일지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["일지 템플릿", "템플릿 설정", "AI 일지 설정"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_MESSENGER",
    screen_name: "메신저",
    route: "/messenger",
    file_path: "app/(admin)/messenger.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "학부모에게 개별 또는 단체 메시지를 보내는 화면",
    buttons: [
      { id: "new_message", label: "메시지 작성", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/dashboard"],
    related_api: ["/messages", "/diary-messages"],
    related_features: ["메신저", "학부모 소통"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["메신저", "메시지", "학부모 메시지", "단체 문자"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_PEOPLE",
    screen_name: "구성원",
    route: "/people",
    file_path: "app/(admin)/people.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "수영장 강사·관리직원을 목록으로 보고 초대·관리하는 화면",
    buttons: [
      { id: "invite_teacher", label: "강사 초대", action_type: "NAVIGATE", target_route: "/invite-qr" },
      { id: "pending_teachers", label: "승인 대기", action_type: "NAVIGATE", target_route: "/people-pending" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/people-teachers", "/people-pending", "/invite-qr"],
    previous_routes: ["/more"],
    related_api: ["/teachers", "/staff"],
    related_features: ["강사 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["강사", "직원", "구성원", "강사 초대", "강사 목록"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_PEOPLE_PENDING",
    screen_name: "승인 대기",
    route: "/people-pending",
    file_path: "app/(admin)/people-pending.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "강사 가입 신청을 검토하고 승인·거절하는 화면",
    buttons: [
      { id: "approve", label: "승인", action_type: "CALL_API" },
      { id: "reject", label: "거절", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/teacher-pending-detail"],
    previous_routes: ["/people"],
    related_api: ["/approvals/teachers"],
    related_features: ["강사 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["강사 승인", "가입 승인", "강사 대기", "승인 요청"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_NOTIFICATIONS",
    screen_name: "알림",
    route: "/notifications",
    file_path: "app/(admin)/notifications.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "관리자 계정의 알림 목록을 조회하는 화면",
    buttons: [
      { id: "mark_all_read", label: "모두 읽음", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/dashboard"],
    related_api: ["/notifications"],
    related_features: ["알림"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["알림", "푸시", "알림 목록"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_SETTINGS",
    screen_name: "설정",
    route: "/settings",
    file_path: "app/(admin)/settings.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "계정 정보·수영장 설정·알림 설정 등 각종 설정 메뉴를 모은 화면",
    buttons: [
      { id: "pool_settings", label: "수영장 정보", action_type: "NAVIGATE", target_route: "/pool-settings" },
      { id: "subscription", label: "구독 관리", action_type: "NAVIGATE", target_route: "/subscription" },
      { id: "push_settings", label: "알림 설정", action_type: "NAVIGATE", target_route: "/push-notification-settings" },
      { id: "my_info", label: "내 정보", action_type: "NAVIGATE", target_route: "/my-info" },
      { id: "logout", label: "로그아웃", action_type: "OTHER" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/pool-settings", "/subscription", "/push-notification-settings", "/my-info"],
    previous_routes: [],
    related_api: [],
    related_features: ["설정"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["설정", "환경 설정", "로그아웃", "계정 설정"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_POOL_SETTINGS",
    screen_name: "수영장 정보",
    route: "/pool-settings",
    file_path: "app/(admin)/pool-settings.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "수영장 이름·주소·운영 시간 등 기본 정보를 수정하는 화면",
    buttons: [
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [
      { field_id: "pool_name", label: "수영장 이름", input_type: "text", required: true },
      { field_id: "address", label: "주소", input_type: "text", required: false },
    ],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/pools/:id"],
    related_features: ["수영장 설정"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["수영장 정보", "수영장 이름", "수영장 설정", "주소 변경"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_SUBSCRIPTION",
    screen_name: "구독 관리",
    route: "/subscription",
    file_path: "app/(admin)/subscription.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "현재 구독 플랜 정보를 조회하고 플랜을 변경하는 화면",
    buttons: [
      { id: "upgrade", label: "플랜 업그레이드", action_type: "NAVIGATE" },
      { id: "billing_history", label: "결제 내역", action_type: "NAVIGATE", target_route: "/billing" },
    ],
    inputs: [],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: ["/billing", "/unit-pricing"],
    previous_routes: ["/settings"],
    related_api: ["/subscription", "/billing"],
    related_features: ["구독", "결제"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["구독", "플랜", "요금제", "결제", "구독 변경"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_BILLING",
    screen_name: "결제 내역",
    route: "/billing",
    file_path: "app/(admin)/billing.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "구독 결제 내역과 청구서를 조회하는 화면",
    buttons: [],
    inputs: [],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/subscription"],
    related_api: ["/billing"],
    related_features: ["결제"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["결제 내역", "청구서", "영수증", "결제 확인"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_MY_INFO",
    screen_name: "내 정보 (관리자)",
    route: "/my-info",
    file_path: "app/(admin)/my-info.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "로그인 계정의 이름·전화번호·비밀번호를 변경하는 화면",
    buttons: [
      { id: "save", label: "저장", action_type: "SUBMIT" },
      { id: "withdraw", label: "탈퇴", action_type: "OPEN_MODAL" },
    ],
    inputs: [
      { field_id: "name", label: "이름", input_type: "text", required: true },
      { field_id: "phone", label: "전화번호", input_type: "phone", required: false },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/auth/me", "/users/:id"],
    related_features: ["계정 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["내 정보", "이름 변경", "전화번호 변경", "비밀번호 변경", "회원 탈퇴"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_INVITE_QR",
    screen_name: "초대 QR",
    route: "/invite-qr",
    file_path: "app/(admin)/invite-qr.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "강사·학부모 초대용 QR 코드와 링크를 생성하는 화면",
    buttons: [
      { id: "share_link", label: "링크 공유", action_type: "OTHER" },
      { id: "copy_link", label: "링크 복사", action_type: "OTHER" },
    ],
    inputs: [],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/people"],
    related_api: ["/invite"],
    related_features: ["초대"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["QR", "초대", "초대 링크", "초대 코드", "강사 초대", "학부모 초대"],
    deep_link: "swimnote.app/join",
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_APPROVALS",
    screen_name: "승인 요청",
    route: "/approvals",
    file_path: "app/(admin)/approvals.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "보강·반 변경 등 각종 승인 요청을 목록으로 보고 처리하는 화면",
    buttons: [
      { id: "approve", label: "승인", action_type: "CALL_API" },
      { id: "reject", label: "거절", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/dashboard"],
    related_api: ["/approvals"],
    related_features: ["승인"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["승인", "승인 요청", "요청 처리", "반 변경 승인"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_NOTICES",
    screen_name: "공지사항",
    route: "/notices",
    file_path: "app/(admin)/notices.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "수영장 공지사항을 작성하고 관리하는 화면",
    buttons: [
      { id: "add_notice", label: "공지 작성", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/more"],
    related_api: ["/notices"],
    related_features: ["공지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["공지", "공지사항", "공지 작성"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_PHOTO_UPLOAD",
    screen_name: "사진 업로드",
    route: "/photo-upload",
    file_path: "app/(admin)/photo-upload.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "수업 사진을 앨범에 업로드하는 화면",
    buttons: [
      { id: "select_photos", label: "사진 선택", action_type: "UPLOAD" },
      { id: "upload", label: "업로드", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/more"],
    related_api: ["/photos", "/media"],
    related_features: ["앨범", "사진"],
    common_errors: ["업로드 용량 초과"],
    known_solutions: [],
    support_keywords: ["사진", "사진 업로드", "앨범", "사진 추가"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_SUPPORT_CHAT",
    screen_name: "1:1 문의 (관리자)",
    route: "/support-chat",
    file_path: "app/(admin)/support-chat.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "스윔노트 고객센터에 AI 또는 상담사에게 문의하는 화면",
    buttons: [
      { id: "send_message", label: "메시지 전송", action_type: "CALL_API" },
    ],
    inputs: [
      { field_id: "message", label: "문의 내용", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/more", "/help"],
    related_api: ["/support/cases", "/support/cases/:id/messages"],
    related_features: ["고객센터"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["고객센터", "문의", "1:1 문의", "상담", "채팅"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_HELP",
    screen_name: "도움말",
    route: "/help",
    file_path: "app/(admin)/help.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "자주 묻는 질문(FAQ)과 고객센터 진입점을 제공하는 화면",
    buttons: [
      { id: "go_support", label: "문의하기", action_type: "NAVIGATE", target_route: "/support-chat" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/support-chat"],
    previous_routes: ["/more"],
    related_api: [],
    related_features: ["고객센터"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["도움말", "FAQ", "고객센터", "문의"],
    frontend_map_version: V,
  },
  // ── X 모드 전용 화면 ───────────────────────────────────────────────────
  {
    screen_id: "ADMIN_X_MODE_HUB",
    screen_name: "X 모드 허브",
    route: "/x-mode-hub",
    file_path: "app/(admin)/x-mode-hub.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["x", "x_pending"],
    purpose: "X 모드(수영장 X 서비스) 기능 전체를 소개하고 진입점을 제공하는 허브 화면",
    buttons: [
      { id: "go_x_growth", label: "성장 관리", action_type: "NAVIGATE", target_route: "/x-growth" },
      { id: "go_x_setup", label: "X 설정", action_type: "NAVIGATE", target_route: "/x-setup" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: ["/x-growth", "/x-setup", "/x-subscription"],
    previous_routes: ["/dashboard"],
    related_api: ["/x/mode"],
    related_features: ["X 모드"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["X 모드", "X 서비스", "X허브", "스윔노트 X"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_X_GROWTH",
    screen_name: "성장 관리 (관리자 X)",
    route: "/x-growth",
    file_path: "app/(admin)/x-growth.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["x"],
    purpose: "X 모드에서 학생별 성장 데이터를 확인하고 성장 리포트를 관리하는 화면",
    buttons: [
      { id: "view_report", label: "리포트 보기", action_type: "NAVIGATE" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: [],
    previous_routes: ["/x-mode-hub"],
    related_api: ["/x/growth", "/growth-events"],
    related_features: ["X 모드", "성장 리포트"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["성장 리포트", "성장 데이터", "X 성장", "리포트"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_X_SETUP",
    screen_name: "X 설정",
    route: "/x-setup",
    file_path: "app/(admin)/x-setup.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["x", "x_pending"],
    purpose: "X 모드 활성화를 위해 수영장 자료를 제출하는 설정 화면",
    buttons: [
      { id: "submit_docs", label: "자료 제출", action_type: "UPLOAD" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: [],
    previous_routes: ["/x-mode-hub"],
    related_api: ["/x/setup"],
    related_features: ["X 모드 설정"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["X 설정", "X 자료 제출", "X 모드 설정", "커리큘럼 업로드"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_X_SUBSCRIPTION",
    screen_name: "X 구독",
    route: "/x-subscription",
    file_path: "app/(admin)/x-subscription.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x", "x_pending"],
    purpose: "X 모드 구독 및 결제를 관리하는 화면 (인앱 결제)",
    buttons: [
      { id: "subscribe", label: "X 구독 시작", action_type: "CALL_API" },
      { id: "restore", label: "구독 복원", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/x-mode-hub", "/settings"],
    related_api: ["/x/billing", "/x/entitlement"],
    related_features: ["X 모드", "결제"],
    common_errors: ["구독 복원 실패", "결제 처리 중 오류"],
    known_solutions: [],
    support_keywords: ["X 구독", "X 결제", "인앱 결제", "구독 복원"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_MODE",
    screen_name: "모드 선택",
    route: "/mode",
    file_path: "app/(admin)/mode.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "Normal 모드와 X 모드 간 전환을 선택하는 화면",
    buttons: [
      { id: "switch_normal", label: "Normal 모드", action_type: "OTHER" },
      { id: "switch_x", label: "X 모드", action_type: "OTHER" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: ["/dashboard"],
    previous_routes: [],
    related_api: ["/x/mode"],
    related_features: ["X 모드"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["모드 전환", "X 모드 전환", "Normal 모드", "모드 선택"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_LEVEL_SETTINGS",
    screen_name: "레벨 설정",
    route: "/level-settings",
    file_path: "app/(admin)/level-settings.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "수영장 레벨 체계(기초/중급/고급 등)를 정의하는 화면",
    buttons: [
      { id: "add_level", label: "레벨 추가", action_type: "OPEN_MODAL" },
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/levels"],
    related_features: ["레벨"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["레벨", "레벨 설정", "수영 레벨", "등급"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_MAKEUP_POLICY",
    screen_name: "보강 정책",
    route: "/makeup-policy",
    file_path: "app/(admin)/makeup-policy.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "보강 신청 가능 기간·횟수 등 보강 정책을 설정하는 화면",
    buttons: [
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/makeup-policy"],
    related_features: ["보강"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["보강 정책", "보강 규칙", "보강 기간"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_REFUND_POLICY",
    screen_name: "환불 정책",
    route: "/refund-policy",
    file_path: "app/(admin)/refund-policy.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "수강료 환불 조건·기준을 설정하고 안내 문구를 관리하는 화면",
    buttons: [
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/refund-policy"],
    related_features: ["환불"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["환불", "환불 정책", "수강료 환불"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_OPS_HUB",
    screen_name: "운영 허브",
    route: "/ops-hub",
    file_path: "app/(admin)/ops-hub.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "운영 관련 고급 기능(정산·데이터·통계)을 모아두는 허브 화면",
    buttons: [
      { id: "settlement", label: "정산", action_type: "NAVIGATE", target_route: "/settlement" },
      { id: "data_management", label: "데이터 관리", action_type: "NAVIGATE", target_route: "/data-management" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/settlement", "/data-management", "/admin-revenue"],
    previous_routes: ["/dashboard"],
    related_api: [],
    related_features: ["운영", "정산"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["운영", "정산", "수입", "데이터"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_PUSH_NOTIFICATION_SETTINGS",
    screen_name: "알림 설정",
    route: "/push-notification-settings",
    file_path: "app/(admin)/push-notification-settings.tsx",
    available_roles: ["pool_admin", "sub_admin"],
    available_modes: ["normal", "x"],
    purpose: "수업·보강·결제 등 알림 수신 항목을 개별로 켜고 끄는 화면",
    buttons: [
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/push-settings"],
    related_features: ["알림"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["알림 설정", "푸시 알림", "알림 끄기", "알림 켜기"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_WEB_PIN_SETTINGS",
    screen_name: "웹 PIN 설정",
    route: "/web-pin-settings",
    file_path: "app/(admin)/web-pin-settings.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "학부모 홈페이지 출결 PIN을 설정하는 화면",
    buttons: [
      { id: "save_pin", label: "PIN 저장", action_type: "SUBMIT" },
    ],
    inputs: [
      { field_id: "pin", label: "PIN 번호", input_type: "number", required: true },
    ],
    permissions: ["pool_admin_only"],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/pool/web-pin"],
    related_features: ["웹 PIN"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["웹 PIN", "PIN 설정", "출결 PIN", "홈페이지 PIN"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_INQUIRIES",
    screen_name: "문의 관리 (관리자)",
    route: "/inquiries",
    file_path: "app/(admin)/inquiries.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "학부모 업무 문의·요청을 목록으로 확인하고 답변하는 화면",
    buttons: [
      { id: "reply", label: "답변하기", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/more"],
    related_api: ["/inquiries", "/requests"],
    related_features: ["업무 요청"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["문의", "업무 요청", "답변", "학부모 문의"],
    frontend_map_version: V,
  },
  {
    screen_id: "ADMIN_TEACHER_HUB",
    screen_name: "강사 허브",
    route: "/teacher-hub",
    file_path: "app/(admin)/teacher-hub.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal", "x"],
    purpose: "강사 피드백·일지·스케줄을 관리자가 모아 볼 수 있는 허브 화면",
    buttons: [],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/diary-teacher-entries", "/people-teachers"],
    previous_routes: ["/more"],
    related_api: [],
    related_features: ["강사 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["강사 허브", "강사 관리", "강사 현황"],
    frontend_map_version: V,
  },
];

// ─── TEACHER SCREENS ──────────────────────────────────────────────────────────

const teacherScreens: FrontendScreen[] = [
  {
    screen_id: "TEACHER_TODAY_SCHEDULE",
    screen_name: "오늘 스케줄 (강사)",
    route: "/today-schedule",
    file_path: "app/(teacher)/today-schedule.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 오늘 담당 수업과 학생 출결을 확인하고 처리하는 메인 화면",
    buttons: [
      { id: "write_diary", label: "일지 작성", action_type: "NAVIGATE", target_route: "/diary" },
      { id: "check_attendance", label: "출결 체크", action_type: "CALL_API" },
      { id: "request_makeup", label: "보강 신청", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: ["xmode"],
    next_routes: ["/diary", "/attendance"],
    previous_routes: [],
    related_api: ["/schedules/today", "/attendance"],
    related_features: ["스케줄", "출결"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["오늘 스케줄", "오늘 수업", "수업 목록", "강사 홈"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_DIARY",
    screen_name: "수업 일지 (강사)",
    route: "/diary",
    file_path: "app/(teacher)/diary.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 담당 수업의 일지를 작성하는 화면 (AI 초안 지원)",
    buttons: [
      { id: "ai_draft", label: "AI 초안 생성", action_type: "CALL_API", notes: "X 모드에서 강화" },
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [
      { field_id: "content", label: "일지 내용", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: ["xmode"],
    next_routes: ["/diary-index"],
    previous_routes: ["/today-schedule"],
    related_api: ["/teacher-diary", "/ai/diary-generate"],
    related_features: ["수업 일지", "AI 일지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["수업 일지", "일지 작성", "AI 일지", "강사 일지"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_DIARY_INDEX",
    screen_name: "일지 목록 (강사)",
    route: "/diary-index",
    file_path: "app/(teacher)/diary-index.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 본인이 작성한 일지 목록을 확인하는 화면",
    buttons: [],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/diary"],
    previous_routes: ["/today-schedule"],
    related_api: ["/teacher-diary"],
    related_features: ["수업 일지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["일지 목록", "내 일지", "일지 확인"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_ATTENDANCE",
    screen_name: "출결 (강사)",
    route: "/attendance",
    file_path: "app/(teacher)/attendance.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 담당 반의 출결을 체크하는 화면",
    buttons: [
      { id: "check", label: "출결 저장", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/makeups"],
    previous_routes: ["/today-schedule"],
    related_api: ["/attendance"],
    related_features: ["출결"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["출결", "출석 체크", "결석 처리"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_STUDENTS",
    screen_name: "학생 목록 (강사)",
    route: "/students",
    file_path: "app/(teacher)/students.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 담당하는 학생 목록을 조회하는 화면",
    buttons: [
      { id: "student_detail", label: "학생 상세", action_type: "NAVIGATE", target_route: "/student-detail" },
    ],
    inputs: [
      { field_id: "search", label: "학생 검색", input_type: "text", required: false },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: ["/student-detail"],
    previous_routes: ["/today-schedule"],
    related_api: ["/students"],
    related_features: ["학생 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["학생", "학생 목록", "내 학생"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_MAKEUPS",
    screen_name: "보강 (강사)",
    route: "/makeups",
    file_path: "app/(teacher)/makeups.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 담당 학생의 보강 일정을 확인하고 처리하는 화면",
    buttons: [
      { id: "confirm_makeup", label: "보강 확인", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/today-schedule"],
    related_api: ["/makeups"],
    related_features: ["보강"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["보강", "강사 보강", "보강 일정"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_MY_SCHEDULE",
    screen_name: "내 스케줄 (강사)",
    route: "/my-schedule",
    file_path: "app/(teacher)/my-schedule.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 자신의 전체 수업 스케줄을 캘린더로 확인하는 화면",
    buttons: [],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/today-schedule"],
    related_api: ["/schedules/my"],
    related_features: ["스케줄"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["내 스케줄", "강사 스케줄", "수업 일정", "캘린더"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_PHOTOS",
    screen_name: "사진 (강사)",
    route: "/photos",
    file_path: "app/(teacher)/photos.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 담당 수업 사진을 업로드하고 앨범을 관리하는 화면",
    buttons: [
      { id: "upload_photo", label: "사진 업로드", action_type: "UPLOAD" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/today-schedule"],
    related_api: ["/photos"],
    related_features: ["앨범", "사진"],
    common_errors: ["업로드 용량 초과"],
    known_solutions: [],
    support_keywords: ["사진", "앨범", "사진 업로드"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_NOTICES",
    screen_name: "공지사항 (강사)",
    route: "/notices",
    file_path: "app/(teacher)/notices.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "수영장 공지사항 목록을 확인하는 화면",
    buttons: [],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/today-schedule"],
    related_api: ["/notices"],
    related_features: ["공지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["공지", "공지사항"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_SETTINGS",
    screen_name: "설정 (강사)",
    route: "/settings",
    file_path: "app/(teacher)/settings.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사 계정의 설정·알림·내 정보 메뉴를 모은 화면",
    buttons: [
      { id: "my_info", label: "내 정보", action_type: "NAVIGATE", target_route: "/my-info" },
      { id: "logout", label: "로그아웃", action_type: "OTHER" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/my-info"],
    previous_routes: [],
    related_api: [],
    related_features: ["설정"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["설정", "강사 설정", "로그아웃"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_MY_INFO",
    screen_name: "내 정보 (강사)",
    route: "/my-info",
    file_path: "app/(teacher)/my-info.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사 이름·전화번호·비밀번호를 변경하는 화면",
    buttons: [
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [
      { field_id: "name", label: "이름", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/auth/me"],
    related_features: ["계정 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["내 정보", "이름 변경", "비밀번호 변경"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_SUPPORT_CHAT",
    screen_name: "1:1 문의 (강사)",
    route: "/support-chat",
    file_path: "app/(teacher)/support-chat.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 스윔노트 고객센터에 문의하는 화면",
    buttons: [
      { id: "send_message", label: "전송", action_type: "CALL_API" },
    ],
    inputs: [
      { field_id: "message", label: "문의 내용", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/settings"],
    related_api: ["/support/cases"],
    related_features: ["고객센터"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["고객센터", "문의", "1:1 문의"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_X_GROWTH",
    screen_name: "성장 관리 (강사 X)",
    route: "/x-growth",
    file_path: "app/(teacher)/x-growth.tsx",
    available_roles: ["teacher"],
    available_modes: ["x"],
    purpose: "X 모드에서 강사가 담당 학생의 성장 리포트를 검토·승인하는 화면",
    buttons: [
      { id: "approve", label: "리포트 승인", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: ["/growth-report-review"],
    previous_routes: ["/today-schedule"],
    related_api: ["/x/growth", "/growth-events"],
    related_features: ["X 모드", "성장 리포트"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["성장 리포트", "X 성장", "리포트 승인"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_GROWTH_REPORT_REVIEW",
    screen_name: "성장 리포트 검토 (강사)",
    route: "/growth-report-review",
    file_path: "app/(teacher)/growth-report-review.tsx",
    available_roles: ["teacher"],
    available_modes: ["x"],
    purpose: "강사가 AI가 분석한 학생 성장 리포트를 검토하고 승인·수정 요청하는 화면",
    buttons: [
      { id: "approve", label: "승인", action_type: "CALL_API" },
      { id: "request_reanalysis", label: "재분석 요청", action_type: "CALL_API" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: [],
    previous_routes: ["/x-growth"],
    related_api: ["/growth-events/:id/review"],
    related_features: ["X 모드", "성장 리포트"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["성장 리포트 검토", "리포트 승인", "성장 분석"],
    frontend_map_version: V,
  },
  {
    screen_id: "TEACHER_INQUIRIES",
    screen_name: "업무 문의 (강사)",
    route: "/inquiries",
    file_path: "app/(teacher)/inquiries.tsx",
    available_roles: ["teacher"],
    available_modes: ["normal", "x"],
    purpose: "강사가 담당 반 학부모의 업무 문의·요청을 확인하고 답변하는 화면",
    buttons: [
      { id: "reply", label: "답변", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/today-schedule"],
    related_api: ["/inquiries"],
    related_features: ["업무 요청"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["업무 문의", "학부모 요청", "요청 확인"],
    frontend_map_version: V,
  },
];

// ─── PARENT SCREENS ────────────────────────────────────────────────────────────

const parentScreens: FrontendScreen[] = [
  {
    screen_id: "PARENT_HOME",
    screen_name: "학부모 홈",
    route: "/home",
    file_path: "app/(parent)/home.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 자녀의 출결·일지·사진·공지를 한눈에 보는 메인 화면",
    buttons: [
      { id: "diary", label: "일지 보기", action_type: "NAVIGATE", target_route: "/diary" },
      { id: "attendance", label: "출결 확인", action_type: "NAVIGATE", target_route: "/attendance" },
      { id: "photos", label: "앨범", action_type: "NAVIGATE", target_route: "/photos" },
      { id: "requests", label: "내 요청", action_type: "NAVIGATE", target_route: "/requests" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/diary", "/attendance", "/photos", "/requests", "/notices", "/swim-diary"],
    previous_routes: [],
    related_api: ["/parent/summary"],
    related_features: ["학부모 홈"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["학부모 홈", "홈", "메인", "학부모"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_DIARY",
    screen_name: "학부모 일지",
    route: "/diary",
    file_path: "app/(parent)/diary.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 자녀의 수업 일지를 조회하고 댓글을 남기는 화면",
    buttons: [
      { id: "add_comment", label: "댓글 작성", action_type: "NAVIGATE", target_route: "/diary-comments" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/diary-comments"],
    previous_routes: ["/home"],
    related_api: ["/diaries", "/parent/diary"],
    related_features: ["수업 일지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["일지", "수업 일지", "학부모 일지", "일지 댓글"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_DIARY_COMMENTS",
    screen_name: "일지 댓글",
    route: "/diary-comments",
    file_path: "app/(parent)/diary-comments.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 수업 일지에 댓글·답글을 작성하고 읽는 화면",
    buttons: [
      { id: "send_comment", label: "댓글 전송", action_type: "CALL_API" },
    ],
    inputs: [
      { field_id: "comment", label: "댓글 내용", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/diary"],
    related_api: ["/diaries/:id/comments"],
    related_features: ["수업 일지", "댓글"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["댓글", "일지 댓글", "일지 답글"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_ATTENDANCE",
    screen_name: "출결 확인 (학부모)",
    route: "/attendance",
    file_path: "app/(parent)/attendance.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 자녀의 출결 현황과 이력을 조회하는 화면",
    buttons: [
      { id: "request_makeup", label: "보강 신청", action_type: "REQUEST" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/attendance-history"],
    previous_routes: ["/home"],
    related_api: ["/parent/attendance"],
    related_features: ["출결", "보강"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["출결", "출석", "결석", "보강 신청", "학부모 출결"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_PHOTOS",
    screen_name: "앨범 (학부모)",
    route: "/photos",
    file_path: "app/(parent)/photos.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 자녀 수업 사진을 앨범에서 조회하고 다운로드하는 화면",
    buttons: [
      { id: "download", label: "사진 저장", action_type: "DOWNLOAD" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/home"],
    related_api: ["/parent/photos"],
    related_features: ["앨범", "사진"],
    common_errors: ["사진 저장 실패"],
    known_solutions: [],
    support_keywords: ["사진", "앨범", "수업 사진", "사진 저장", "다운로드"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_SWIM_DIARY",
    screen_name: "수영 일지 (학부모)",
    route: "/swim-diary",
    file_path: "app/(parent)/swim-diary.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 자녀의 수영 수업 일지를 날짜별로 조회하는 화면",
    buttons: [],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/home"],
    related_api: ["/parent/swim-diary"],
    related_features: ["수업 일지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["수영 일지", "일지 보기"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_REQUESTS",
    screen_name: "내 요청 (학부모)",
    route: "/requests",
    file_path: "app/(parent)/requests.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 수영장에 제출한 요청(보강·반 변경 등)의 처리 상태를 확인하는 화면",
    buttons: [
      { id: "new_request", label: "새 요청", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/home", "/more"],
    related_api: ["/parent/requests"],
    related_features: ["업무 요청"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["내 요청", "요청 현황", "보강 요청", "반 변경 요청"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_GROWTH_REPORT",
    screen_name: "성장 리포트 (학부모)",
    route: "/growth-report",
    file_path: "app/(parent)/growth-report.tsx",
    available_roles: ["parent"],
    available_modes: ["x"],
    purpose: "학부모가 자녀의 X 모드 성장 리포트 목록을 확인하는 화면",
    buttons: [
      { id: "view_detail", label: "상세 보기", action_type: "NAVIGATE", target_route: "/growth-report-detail" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: ["/growth-report-detail"],
    previous_routes: ["/home"],
    related_api: ["/parent/growth-reports"],
    related_features: ["X 모드", "성장 리포트"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["성장 리포트", "리포트", "성장 분석"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_GROWTH_REPORT_DETAIL",
    screen_name: "성장 리포트 상세 (학부모)",
    route: "/growth-report-detail",
    file_path: "app/(parent)/growth-report-detail.tsx",
    available_roles: ["parent"],
    available_modes: ["x"],
    purpose: "개별 성장 리포트의 분석 내용과 AI 피드백을 상세히 보는 화면",
    buttons: [
      { id: "answer_questions", label: "질문 답변", action_type: "NAVIGATE", target_route: "/growth-report-questions" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: ["/growth-report-questions"],
    previous_routes: ["/growth-report"],
    related_api: ["/parent/growth-reports/:id"],
    related_features: ["X 모드", "성장 리포트"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["성장 리포트 상세", "성장 분석 내용", "AI 피드백"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_GROWTH_REPORT_QUESTIONS",
    screen_name: "성장 리포트 질문 (학부모)",
    route: "/growth-report-questions",
    file_path: "app/(parent)/growth-report-questions.tsx",
    available_roles: ["parent"],
    available_modes: ["x"],
    purpose: "학부모가 자녀 성장 분석을 위한 설문 질문에 답변하는 화면",
    buttons: [
      { id: "submit", label: "답변 제출", action_type: "SUBMIT" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: ["/growth-report"],
    previous_routes: ["/growth-report-detail"],
    related_api: ["/parent/growth-reports/:id/questions"],
    related_features: ["X 모드", "성장 리포트"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["성장 설문", "성장 질문", "리포트 답변"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_CURRICULUM_CHAT",
    screen_name: "커리큘럼 AI 문의 (학부모)",
    route: "/curriculum-chat",
    file_path: "app/(parent)/curriculum-chat.tsx",
    available_roles: ["parent"],
    available_modes: ["x"],
    purpose: "학부모가 자녀의 수영 커리큘럼에 대해 AI에게 질문하는 채팅 화면",
    buttons: [
      { id: "send", label: "전송", action_type: "CALL_API" },
    ],
    inputs: [
      { field_id: "question", label: "질문 입력", input_type: "text", required: true },
    ],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: [],
    previous_routes: ["/home"],
    related_api: ["/parent/curriculum-search"],
    related_features: ["X 모드", "AI", "커리큘럼"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["커리큘럼", "AI 문의", "수영 커리큘럼", "커리큘럼 채팅"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_X_GROWTH",
    screen_name: "성장 관리 (학부모 X)",
    route: "/x-growth",
    file_path: "app/(parent)/x-growth.tsx",
    available_roles: ["parent"],
    available_modes: ["x"],
    purpose: "학부모가 자녀의 X 모드 성장 현황을 종합적으로 확인하는 허브 화면",
    buttons: [
      { id: "view_report", label: "리포트 보기", action_type: "NAVIGATE", target_route: "/growth-report" },
      { id: "curriculum_chat", label: "커리큘럼 문의", action_type: "NAVIGATE", target_route: "/curriculum-chat" },
    ],
    inputs: [],
    permissions: ["x_entitlement"],
    feature_flags: ["xmode"],
    next_routes: ["/growth-report", "/curriculum-chat"],
    previous_routes: ["/home"],
    related_api: ["/x/growth"],
    related_features: ["X 모드", "성장 리포트"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["X 성장", "성장 허브", "학부모 X 모드"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_NOTICES",
    screen_name: "공지사항 (학부모)",
    route: "/notices",
    file_path: "app/(parent)/notices.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "수영장 공지사항 목록을 확인하는 화면",
    buttons: [
      { id: "notice_detail", label: "공지 상세", action_type: "NAVIGATE", target_route: "/notice-detail" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/notice-detail"],
    previous_routes: ["/home"],
    related_api: ["/notices"],
    related_features: ["공지"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["공지", "공지사항", "수영장 공지"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_NOTIFICATIONS",
    screen_name: "알림 (학부모)",
    route: "/notifications",
    file_path: "app/(parent)/notifications.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모 알림 목록을 조회하는 화면",
    buttons: [],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/home"],
    related_api: ["/notifications"],
    related_features: ["알림"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["알림", "학부모 알림"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_PUSH_SETTINGS",
    screen_name: "알림 설정 (학부모)",
    route: "/push-settings",
    file_path: "app/(parent)/push-settings.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 수업·보강·일지 알림 수신을 개별로 설정하는 화면",
    buttons: [
      { id: "save", label: "저장", action_type: "SUBMIT" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/more"],
    related_api: ["/push-settings"],
    related_features: ["알림"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["알림 설정", "학부모 알림 설정", "푸시 알림 끄기"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_MY_INFO",
    screen_name: "내 정보 (학부모)",
    route: "/my-info",
    file_path: "app/(parent)/my-info.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모 계정의 이름·전화번호를 수정하는 화면",
    buttons: [
      { id: "save", label: "저장", action_type: "SUBMIT" },
      { id: "withdraw", label: "탈퇴", action_type: "OPEN_MODAL" },
    ],
    inputs: [
      { field_id: "name", label: "닉네임", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/more"],
    related_api: ["/auth/me"],
    related_features: ["계정 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["내 정보", "학부모 정보", "닉네임 변경", "탈퇴"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_CHILDREN",
    screen_name: "자녀 관리",
    route: "/children",
    file_path: "app/(parent)/children.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "등록된 자녀 목록을 조회하고 자녀를 추가·연결하는 화면",
    buttons: [
      { id: "add_child", label: "자녀 추가", action_type: "NAVIGATE", target_route: "/add-child" },
      { id: "link_child", label: "자녀 연결", action_type: "NAVIGATE", target_route: "/link-child" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/add-child", "/link-child", "/child-profile"],
    previous_routes: ["/more"],
    related_api: ["/parent/students"],
    related_features: ["자녀 관리"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["자녀", "자녀 추가", "자녀 연결", "아이", "자녀 관리"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_SUPPORT_CHAT",
    screen_name: "1:1 문의 (학부모)",
    route: "/support-chat",
    file_path: "app/(parent)/support-chat.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 스윔노트 고객센터에 문의하는 화면",
    buttons: [
      { id: "send", label: "전송", action_type: "CALL_API" },
    ],
    inputs: [
      { field_id: "message", label: "문의 내용", input_type: "text", required: true },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/more"],
    related_api: ["/support/cases"],
    related_features: ["고객센터"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["고객센터", "문의", "1:1 문의"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_INQUIRIES",
    screen_name: "업무 문의 (학부모)",
    route: "/inquiries",
    file_path: "app/(parent)/inquiries.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 수영장 강사·관리자에게 업무 요청(보강·반 변경 등)을 보내는 화면",
    buttons: [
      { id: "new_inquiry", label: "새 문의", action_type: "OPEN_MODAL" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/home", "/more"],
    related_api: ["/inquiries"],
    related_features: ["업무 요청"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["업무 문의", "요청하기", "학부모 요청"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_LEVEL",
    screen_name: "수영 레벨 (학부모)",
    route: "/level",
    file_path: "app/(parent)/level.tsx",
    available_roles: ["parent"],
    available_modes: ["normal", "x"],
    purpose: "학부모가 자녀의 현재 수영 레벨과 진급 조건을 확인하는 화면",
    buttons: [],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: [],
    previous_routes: ["/home"],
    related_api: ["/parent/level"],
    related_features: ["레벨"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["레벨", "수영 레벨", "등급", "진급"],
    frontend_map_version: V,
  },
];

// ─── COMMON / PUBLIC SCREENS ──────────────────────────────────────────────────

const commonScreens: FrontendScreen[] = [
  {
    screen_id: "POOL_APPLY",
    screen_name: "수영장 등록 신청",
    route: "/pool-apply",
    file_path: "app/pool-apply.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal"],
    purpose: "신규 수영장 관리자가 스윔노트에 수영장 등록을 신청하는 화면",
    buttons: [
      { id: "submit", label: "등록 신청", action_type: "SUBMIT" },
    ],
    inputs: [
      { field_id: "pool_name", label: "수영장 이름", input_type: "text", required: true },
      { field_id: "address", label: "주소", input_type: "text", required: true },
      { field_id: "phone", label: "대표 전화", input_type: "phone", required: false },
    ],
    permissions: [],
    feature_flags: [],
    next_routes: ["/pending"],
    previous_routes: ["/signup"],
    related_api: ["/pools/apply"],
    related_features: ["수영장 등록"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["수영장 등록", "등록 신청", "수영장 개설"],
    frontend_map_version: V,
  },
  {
    screen_id: "POOL_PENDING",
    screen_name: "승인 대기 중",
    route: "/pending",
    file_path: "app/pending.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal"],
    purpose: "수영장 등록 신청 후 운영팀 승인을 대기하는 안내 화면",
    buttons: [],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/dashboard"],
    previous_routes: ["/pool-apply"],
    related_api: [],
    related_features: ["수영장 등록"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["승인 대기", "수영장 승인", "검토 중"],
    frontend_map_version: V,
  },
  {
    screen_id: "SUPPORT_TICKET_LIST",
    screen_name: "지원 티켓 목록 (레거시)",
    route: "/support-ticket-list",
    file_path: "app/support-ticket-list.tsx",
    available_roles: ["pool_admin", "teacher"],
    available_modes: ["normal", "x"],
    purpose: "기존 고객 지원 티켓 목록을 조회하는 레거시 화면",
    buttons: [
      { id: "write_ticket", label: "문의 작성", action_type: "NAVIGATE", target_route: "/support-ticket-write" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/support-ticket-detail", "/support-ticket-write"],
    previous_routes: [],
    related_api: ["/support-tickets"],
    related_features: ["고객센터"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["지원 티켓", "문의 목록", "내 문의"],
    frontend_map_version: V,
  },
  {
    screen_id: "SUBSCRIPTION_EXPIRED",
    screen_name: "구독 만료",
    route: "/subscription-expired",
    file_path: "app/subscription-expired.tsx",
    available_roles: ["pool_admin"],
    available_modes: ["normal"],
    purpose: "구독이 만료되어 기능이 제한됨을 안내하고 구독 갱신을 유도하는 화면",
    buttons: [
      { id: "renew", label: "구독 갱신", action_type: "NAVIGATE", target_route: "/subscription" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/subscription"],
    previous_routes: [],
    related_api: [],
    related_features: ["구독"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["구독 만료", "플랜 만료", "기능 제한"],
    frontend_map_version: V,
  },
  {
    screen_id: "PARENT_INVITE_INFO",
    screen_name: "학부모 초대 안내",
    route: "/parent-invite-info",
    file_path: "app/parent-invite-info.tsx",
    available_roles: ["parent"],
    available_modes: ["normal"],
    purpose: "수영장 초대 링크로 진입한 학부모에게 가입 안내를 제공하는 화면",
    buttons: [
      { id: "join", label: "가입하기", action_type: "NAVIGATE", target_route: "/parent-login" },
    ],
    inputs: [],
    permissions: [],
    feature_flags: [],
    next_routes: ["/parent-login"],
    previous_routes: [],
    related_api: [],
    related_features: ["초대"],
    common_errors: [],
    known_solutions: [],
    support_keywords: ["초대 링크", "학부모 가입", "수영장 참여"],
    deep_link: "swimnote.app/join?role=parent",
    frontend_map_version: V,
  },
];

// ─── FULL REGISTRY ─────────────────────────────────────────────────────────────

export const FRONTEND_MAP_REGISTRY: FrontendScreen[] = [
  ...authScreens,
  ...adminScreens,
  ...teacherScreens,
  ...parentScreens,
  ...commonScreens,
];

/** screen_id → FrontendScreen 빠른 조회 맵 */
export const SCREEN_BY_ID = new Map<string, FrontendScreen>(
  FRONTEND_MAP_REGISTRY.map((s) => [s.screen_id, s])
);

/** route → screen_id 조회 맵 (role 무관, 같은 route 경로가 여러 role에 존재할 수 있음) */
export const SCREENS_BY_ROUTE = new Map<string, FrontendScreen[]>();
for (const screen of FRONTEND_MAP_REGISTRY) {
  const list = SCREENS_BY_ROUTE.get(screen.route) ?? [];
  list.push(screen);
  SCREENS_BY_ROUTE.set(screen.route, list);
}
