// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ai-modal-states/ErrorState.tsx": () => import("../components/mockups/ai-modal-states/ErrorState.tsx"),
  "./components/mockups/ai-modal-states/InputState.tsx": () => import("../components/mockups/ai-modal-states/InputState.tsx"),
  "./components/mockups/ai-modal-states/LongResultList.tsx": () => import("../components/mockups/ai-modal-states/LongResultList.tsx"),
  "./components/mockups/ai-modal-states/LongResultParagraph.tsx": () => import("../components/mockups/ai-modal-states/LongResultParagraph.tsx"),
  "./components/mockups/ai-modal-states/LongResultScrollTest.tsx": () => import("../components/mockups/ai-modal-states/LongResultScrollTest.tsx"),
  "./components/mockups/ai-modal-states/ProcessingState.tsx": () => import("../components/mockups/ai-modal-states/ProcessingState.tsx"),
  "./components/mockups/ai-modal-states/ResultState.tsx": () => import("../components/mockups/ai-modal-states/ResultState.tsx"),
  "./components/mockups/icon-color/ColorSystem.tsx": () => import("../components/mockups/icon-color/ColorSystem.tsx"),
  "./components/mockups/danggeun-style/AdminDanggeun.tsx": () => import("../components/mockups/danggeun-style/AdminDanggeun.tsx"),
  "./components/mockups/danggeun-style/TeacherDanggeun.tsx": () => import("../components/mockups/danggeun-style/TeacherDanggeun.tsx"),
  "./components/mockups/diary-photo-strip/DiaryCard.tsx": () => import("../components/mockups/diary-photo-strip/DiaryCard.tsx"),
  "./components/mockups/icon-compare/Lucide.tsx": () => import("../components/mockups/icon-compare/Lucide.tsx"),
  "./components/mockups/icon-compare/Phosphor.tsx": () => import("../components/mockups/icon-compare/Phosphor.tsx"),
  "./components/mockups/icon-compare/Tabler.tsx": () => import("../components/mockups/icon-compare/Tabler.tsx"),
  "./components/mockups/phosphor-sample/Attendance.tsx": () => import("../components/mockups/phosphor-sample/Attendance.tsx"),
  "./components/mockups/phosphor-sample/Dashboard.tsx": () => import("../components/mockups/phosphor-sample/Dashboard.tsx"),
  "./components/mockups/phosphor-sample/MemberList.tsx": () => import("../components/mockups/phosphor-sample/MemberList.tsx"),
  "./components/mockups/tab-compare/TabBarCompare.tsx": () => import("../components/mockups/tab-compare/TabBarCompare.tsx"),
  "./components/mockups/teacher-color/TeacherHome.tsx": () => import("../components/mockups/teacher-color/TeacherHome.tsx"),
  "./components/mockups/teacher-color/TeacherSettings.tsx": () => import("../components/mockups/teacher-color/TeacherSettings.tsx")
};
