// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/icon-color/ColorSystem.tsx": () => import("../components/mockups/icon-color/ColorSystem.tsx"),
  "./components/mockups/icon-compare/Lucide.tsx": () => import("../components/mockups/icon-compare/Lucide.tsx"),
  "./components/mockups/icon-compare/Phosphor.tsx": () => import("../components/mockups/icon-compare/Phosphor.tsx"),
  "./components/mockups/icon-compare/Tabler.tsx": () => import("../components/mockups/icon-compare/Tabler.tsx"),
  "./components/mockups/phosphor-sample/Attendance.tsx": () => import("../components/mockups/phosphor-sample/Attendance.tsx"),
  "./components/mockups/phosphor-sample/Dashboard.tsx": () => import("../components/mockups/phosphor-sample/Dashboard.tsx"),
  "./components/mockups/phosphor-sample/MemberList.tsx": () => import("../components/mockups/phosphor-sample/MemberList.tsx"),
  "./components/mockups/teacher-color/TeacherHome.tsx": () => import("../components/mockups/teacher-color/TeacherHome.tsx"),
  "./components/mockups/teacher-color/TeacherSettings.tsx": () => import("../components/mockups/teacher-color/TeacherSettings.tsx")
};
