// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/phosphor-sample/Attendance.tsx": () => import("../components/mockups/phosphor-sample/Attendance.tsx"),
  "./components/mockups/phosphor-sample/Dashboard.tsx": () => import("../components/mockups/phosphor-sample/Dashboard.tsx"),
  "./components/mockups/phosphor-sample/MemberList.tsx": () => import("../components/mockups/phosphor-sample/MemberList.tsx")
};
