import React from "react";
import {
  Activity, CircleAlert, OctagonAlert, TriangleAlert, Anchor, Archive,
  ArrowLeft, ArrowRight, CircleArrowRight, CircleArrowUp, AtSign, Award,
  Building2, ChartBar, Bell, BellOff, Book, Bookmark, BookmarkPlus, BookOpen,
  Briefcase, Calendar, CalendarCheck, CalendarDays,
  Camera, Check, CircleCheck, SquareCheck, ChevronDown, ChevronLeft,
  ChevronRight, ChevronUp, Circle, CircleDollarSign, CircleMinus,
  Clipboard, ClipboardList, Clock, Copy, CornerLeftUp, Cpu, CreditCard,
  Crown, Database, DollarSign, Download, CloudDownload, Droplet, Pencil, PenLine,
  ExternalLink, Eye, EyeOff, File, FileCheck, FileText, Flame, FolderSearch,
  Gift, GitBranch, Globe, GraduationCap, Grid2x2,
  HardDrive, Hash, Headphones, Heart, HeartHandshake, Home, Image as ImageIcon,
  Images, Inbox, Info, Key, Layers, LayoutDashboard, Lightbulb, Link, Link2,
  List, ListChecks, Lock, LogIn, LogOut, Mail, MailOpen, MapPin, Menu,
  MessageCircle, MessageSquare, Mic, Minus, Monitor, MoreHorizontal, Package,
  Paperclip, Pause, CirclePause, Phone, PhoneCall, PieChart, Pin, Play,
  Plus, CirclePlus, Printer, Radio, RefreshCcw, RefreshCw,
  Repeat, RotateCcw, Save, Search, Send, Server, Settings, Settings2, Share2,
  Shield, ShieldCheck, ShieldOff, ShoppingBag, ShoppingCart, SlidersHorizontal,
  Smartphone, Smile, Square, CircleStop, Sun, Table, Tag, Target, Terminal,
  ToggleLeft, Trash2, TrendingUp, Trophy, Type, Unlock, Upload, CloudUpload,
  User, UserCheck, UserCog, UserMinus, UserPlus, UserRound, Users, UserX,
  Video, X, CircleX, Zap, ZoomIn,
  LucideProps,
} from "lucide-react-native";

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  activity: Activity,
  "alert-circle": CircleAlert,
  "alert-octagon": OctagonAlert,
  "alert-triangle": TriangleAlert,
  anchor: Anchor,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-right-circle": CircleArrowRight,
  "arrow-up-circle": CircleArrowUp,
  "at-sign": AtSign,
  award: Award,
  "bar-chart-2": ChartBar,
  bell: Bell,
  "bell-off": BellOff,
  book: Book,
  "building-2": Building2,
  bookmark: Bookmark,
  "bookmark-plus": BookmarkPlus,
  "book-open": BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  camera: Camera,
  check: Check,
  "check-circle": CircleCheck,
  "check-square": SquareCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-dollar-sign": CircleDollarSign,
  "circle-minus": CircleMinus,
  clipboard: Clipboard,
  "clipboard-list": ClipboardList,
  clock: Clock,
  copy: Copy,
  "corner-left-up": CornerLeftUp,
  cpu: Cpu,
  "credit-card": CreditCard,
  crown: Crown,
  database: Database,
  "dollar-sign": DollarSign,
  download: Download,
  "download-cloud": CloudDownload,
  droplet: Droplet,
  edit: Pencil,
  "edit-2": PenLine,
  "edit-3": Pencil,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-check": FileCheck,
  "file-text": FileText,
  flame: Flame,
  "folder-search": FolderSearch,
  gift: Gift,
  "git-branch": GitBranch,
  globe: Globe,
  "graduation-cap": GraduationCap,
  grid: Grid2x2,
  "hard-drive": HardDrive,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  home: Home,
  image: ImageIcon,
  images: Images,
  inbox: Inbox,
  info: Info,
  key: Key,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  lightbulb: Lightbulb,
  link: Link,
  "link-2": Link2,
  list: List,
  "list-checks": ListChecks,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  "mail-open": MailOpen,
  "map-pin": MapPin,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  minus: Minus,
  monitor: Monitor,
  "more-horizontal": MoreHorizontal,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  "pause-circle": CirclePause,
  phone: Phone,
  "phone-call": PhoneCall,
  "pie-chart": PieChart,
  pin: Pin,
  play: Play,
  plus: Plus,
  "plus-circle": CirclePlus,
  printer: Printer,
  radio: Radio,
  "refresh-ccw": RefreshCcw,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "rotate-ccw": RotateCcw,
  save: Save,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  "settings-2": Settings2,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  smile: Smile,
  square: Square,
  "stop-circle": CircleStop,
  sun: Sun,
  table: Table,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thumbtack: Pin,
  "toggle-left": ToggleLeft,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  trophy: Trophy,
  type: Type,
  unlock: Unlock,
  upload: Upload,
  "upload-cloud": CloudUpload,
  user: User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-round": UserRound,
  users: Users,
  "user-x": UserX,
  video: Video,
  x: X,
  "x-circle": CircleX,
  zap: Zap,
  "zoom-in": ZoomIn,
};

interface Props extends LucideProps {
  name: string;
}

export function LucideIcon({ name, size = 20, color = "#0F172A", strokeWidth = 2, ...rest }: Props) {
  const IconComponent = ICON_MAP[name] ?? CircleAlert;
  return <IconComponent size={size} color={color} strokeWidth={strokeWidth} {...rest} />;
}
