import React from "react";
import {
  Activity, CircleAlert, OctagonAlert, TriangleAlert, Anchor, Archive,
  ArrowLeft, ArrowRight, CircleArrowRight, CircleArrowUp, AtSign, Award,
  ChartBar, Bell, BellOff, Book, Bookmark, BookOpen, Briefcase, Calendar,
  Camera, Check, CircleCheck, SquareCheck, ChevronDown, ChevronLeft,
  ChevronRight, Circle, Clipboard, Clock, Copy, CornerLeftUp, CreditCard,
  Database, DollarSign, Download, CloudDownload, Droplet, Pencil, PenLine,
  ExternalLink, Eye, EyeOff, File, FileText, GitBranch, Globe, Grid2x2,
  HardDrive, Hash, Heart, HeartHandshake, Home, Image as ImageIcon, Inbox, Info, Key, Layers, Link,
  List, Lock, LogIn, LogOut, Mail, MapPin, Menu, MessageCircle, MessageSquare,
  Mic, Minus, Monitor, Package, Paperclip, Pause, CirclePause, Phone,
  PhoneCall, PieChart, Pin, Plus, CirclePlus, Radio, RefreshCcw, RefreshCw,
  Repeat, RotateCcw, Save, Search, Send, Server, Settings, Share2, Shield,
  ShieldOff, ShoppingBag, ShoppingCart, SlidersHorizontal, Smartphone, Smile,
  Square, CircleStop, Sun, Table, Tag, Target, Terminal, ToggleLeft, Trash2,
  TrendingUp, Type, Unlock, Upload, CloudUpload, User, UserCheck, UserMinus,
  UserPlus, Users, UserX, Video, X, CircleX, Zap,
  LucideProps,
} from "lucide-react-native";

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  activity: Activity,
  "alert-circle": CircleAlert,
  "alert-octagon": OctagonAlert,
  "alert-triangle": TriangleAlert,
  anchor: Anchor,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-right-circle": CircleArrowRight,
  "arrow-up-circle": CircleArrowUp,
  "at-sign": AtSign,
  award: Award,
  "bar-chart-2": ChartBar,
  bell: Bell,
  "bell-off": BellOff,
  book: Book,
  bookmark: Bookmark,
  "book-open": BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "check-circle": CircleCheck,
  "check-square": SquareCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  copy: Copy,
  "corner-left-up": CornerLeftUp,
  "credit-card": CreditCard,
  database: Database,
  "dollar-sign": DollarSign,
  download: Download,
  "download-cloud": CloudDownload,
  droplet: Droplet,
  edit: Pencil,
  "edit-2": PenLine,
  "edit-3": Pencil,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-text": FileText,
  "git-branch": GitBranch,
  globe: Globe,
  grid: Grid2x2,
  "hard-drive": HardDrive,
  hash: Hash,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  home: Home,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  key: Key,
  layers: Layers,
  link: Link,
  list: List,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  minus: Minus,
  monitor: Monitor,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  "pause-circle": CirclePause,
  phone: Phone,
  "phone-call": PhoneCall,
  "pie-chart": PieChart,
  pin: Pin,
  plus: Plus,
  "plus-circle": CirclePlus,
  radio: Radio,
  "refresh-ccw": RefreshCcw,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "rotate-ccw": RotateCcw,
  save: Save,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-off": ShieldOff,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  smile: Smile,
  square: Square,
  "stop-circle": CircleStop,
  sun: Sun,
  table: Table,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thumbtack: Pin,
  "toggle-left": ToggleLeft,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  type: Type,
  unlock: Unlock,
  upload: Upload,
  "upload-cloud": CloudUpload,
  user: User,
  "user-check": UserCheck,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  users: Users,
  "user-x": UserX,
  video: Video,
  x: X,
  "x-circle": CircleX,
  zap: Zap,
};

interface Props extends LucideProps {
  name: string;
}

export function LucideIcon({ name, size = 20, color = "#0F172A", strokeWidth = 2, ...rest }: Props) {
  const IconComponent = ICON_MAP[name] ?? CircleAlert;
  return <IconComponent size={size} color={color} strokeWidth={strokeWidth} {...rest} />;
}
